In [1]:
import numpy as np

In [6]:
a = [1,2,3,4,5]
b = []
for i in range(0,len(a)):
    b.append(a[i]+15)
print(b)

[16, 17, 18, 19, 20]


In [9]:
a = [1,2,3,4,5]
for i in range(0,len(a)):
    a[i] = (a[i]+15)
print(a)

[16, 17, 18, 19, 20]


In [10]:
a = np.array(a)
print(a)

[16 17 18 19 20]


In [11]:
a

array([16, 17, 18, 19, 20])

In [12]:
a+5

array([21, 22, 23, 24, 25])

In [25]:
a = [1,2,3,4,5,6,7,8,9,10]
b = [11,12,13,14,15,16,17,18,19,20]
c = []

In [26]:
for i in a:
    c.append(i+b[i-1])
print(c)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


In [27]:
arr_a = np.array(a)
arr_b = np.array(b)

c = arr_a + arr_b
print(c)

[12 14 16 18 20 22 24 26 28 30]


In [33]:
import time
size_vector = 100000

def pythonlist(size_vector):
    t1 = time.time()
    x = range(size_vector)
    y = range(size_vector)
    t2 = time.time()
    print("python list Load Time : "+ str(t2-t1))
    z = []
    
    t3 = time.time()
    for i in range(len(x)):
        z.append(x[i] + y[i])
    t4 = time.time()
    print("python list for loop : "+ str(t4-t3))
    
    print("python List Total : "+ str(t4-t1))
    
def numpyarray1(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print("numpy array1 Load Time : "+ str(t2-t1))
    
    t3 = time.time()
    z = x + y
    t4 = time.time()
    print("python list for loop : "+ str(t4-t3))
    
    print("python List Total : "+ str(t4-t1))
    
def numpyarray2(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print("numpy array2 Load Time : "+ str(t2-t1))
    
    t3 = time.time()
    z = np.ndarray(size_vector)
    for i in range(len(x)):
        z[i] = x[i] + y[i]
    t4 = time.time()
    print("python list for loop : "+ str(t4-t3))
    
    print("python List Total : "+ str(t4-t1))
    
pythonlist(size_vector)
numpyarray1(size_vector)
numpyarray2(size_vector)

python list Load Time : 0.0
python list for loop : 0.04800271987915039
python List Total : 0.04800271987915039
numpy array1 Load Time : 0.0
python list for loop : 0.0010001659393310547
python List Total : 0.0010001659393310547
numpy array2 Load Time : 0.0
python list for loop : 0.039002180099487305
python List Total : 0.039002180099487305


In [34]:
def square_list0(N):
    squares = []
    for n in range(N):
        squares = squares + [n**2]
    return squares

In [35]:
def square_list1(N):
    squares = []
    for n in range(N):
        squares += [n**2]
    return squares

In [36]:
def square_list2(N):
    squares = []
    for n in range(N):
        squares.append(n**2)
    return squares

In [37]:
def square_list3(N):
    return [n**2 for n in range(N)]

In [38]:
def square_array(N):
    return np.arange(N)**2

In [39]:
n = 100000
print("Number : ", n)
t1 = time.time()
square_list0(n)
t2 = time.time()
print("List0_Try : ", t2-t1)

t1 = time.time()
square_list1(n)
t2 = time.time()
print("List1_Try : ", t2-t1)

t1 = time.time()
square_list2(n)
t2 = time.time()
print("List2_Try : ", t2-t1)

t1 = time.time()
square_list3(n)
t2 = time.time()
print("List3_Try : ", t2-t1)

t1 = time.time()
square_array(n)
t2 = time.time()
print("Array_Try : ", t2-t1)

Number :  100000
List0_Try :  21.74224352836609
List1_Try :  0.052002906799316406
List2_Try :  0.049002885818481445
List3_Try :  0.04600262641906738
Array_Try :  0.0


In [40]:
# 색인
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)

print(list1)
print(arr1)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [41]:
# 정수 인덱스로 리스트와 1차원 numpy 배열 접근 --> 참고)원본은 변경되지 않음!
print(list1[0])
print(arr1[0])
print("\n")
print(list1[1:3])
print(arr1[1:3])
print("\n")
print(list1[3:])
print(arr1[3:])
print("\n")
print(list1[:])
print(arr1[:])

1
1


[2, 3]
[2 3]


[4, 5, 6]
[4 5 6]


[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [62]:
# 행 , 열 리스트 생성
h = np.arange(0,6,1)
v = np.arange(0,51,10)

print(h)
print(v)

# 열 수직배열로 변환
v = np.arange(0,51,10)[:,np.newaxis]
print(v)

# 행열구조 생성
a = np.arange(0,51,10)[:,np.newaxis] + np.arange(0,6,1)
print(a)
print(a[:])

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [64]:
a[0][1]

1

In [65]:
a[0,1]

1

In [66]:
a[0:2,1]

array([ 1, 11])

In [69]:
#pdf 참고하여 샘플 추출
#빨간색
a[0:len(a),2]

array([ 2, 12, 22, 32, 42, 52])

In [71]:
#주황색
a[0,3:5]

array([3, 4])

In [91]:
#초록색
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [89]:
#민트색
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [92]:
#Boolean indexing
arr1 = np.arange(10)
print(arr1)
print(arr1<5)
print(arr1[arr1<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]


In [94]:
# names - 학생이름 / data - 국,영,수,과 순으로 성적부여
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
# 참고) numpy.random.randint(low,high=None,size=None,dtype='l')
data = np.random.randint(low=30,high=100,size=(7,4))
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[83 53 45 76]
 [74 96 41 92]
 [91 63 37 93]
 [92 74 94 83]
 [74 57 62 53]
 [41 50 56 42]
 [71 83 70 62]]


In [98]:
print(names == "Bob")
print(names[names=="Bob"])
print(len(names[names=="Bob"]))

[ True False False  True False False False]
['Bob' 'Bob']
2


In [103]:
print(data[names=="Bob"])

[[83 53 45 76]
 [92 74 94 83]]


In [106]:
print(data[names=="Bob",2:])

[[45 76]
 [94 83]]


In [109]:
print(data[names=="Bob"][0])

[83 53 45 76]


In [113]:
print(data[(names=="Bob")|(names=="Will")])

[[83 53 45 76]
 [91 63 37 93]
 [92 74 94 83]
 [74 57 62 53]]


In [114]:
print(data[(names=="Bob")|(names=="Will"),1::2])

[[53 76]
 [63 93]
 [74 83]
 [57 53]]


In [117]:
# step1)
print(data)
data[data<=70] = 0
data[data>70] = 1
print(data)

[[83 53 45 76]
 [74 96 41 92]
 [91 63 37 93]
 [92 74 94 83]
 [74 57 62 53]
 [41 50 56 42]
 [71 83 70 62]]
[[1 0 0 1]
 [1 1 0 1]
 [1 0 0 1]
 [1 1 1 1]
 [1 0 0 0]
 [0 0 0 0]
 [1 1 0 0]]


In [118]:
# step2)
# 참고) 원하는 값을 찾을 때는 np.where을 사용
# 1로 패스한 사람들의 데이터만 찾음 --> 결과가 어떠한 것을 의미하는지 잘 확인할 것!!!
np.where(data>0)

(array([0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 6, 6], dtype=int64),
 array([0, 3, 0, 1, 3, 0, 3, 0, 1, 2, 3, 0, 0, 1], dtype=int64))

In [119]:
# step3 , 4)
# 이를 바탕으로 이름에 대한 유니크한 index를 찾아서 누가 패스했는지 찾아보자
print(np.unique(np.where(data>0)[0]))
print(names[np.unique(np.where(data>0)[0])])

[0 1 2 3 4 6]
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe']
