In [2]:
import numpy as np

In [3]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [4]:
arr = arr.reshape((4,8))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [5]:
print(arr)
print(arr.T)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
[[ 0  8 16 24]
 [ 1  9 17 25]
 [ 2 10 18 26]
 [ 3 11 19 27]
 [ 4 12 20 28]
 [ 5 13 21 29]
 [ 6 14 22 30]
 [ 7 15 23 31]]


In [6]:
import pandas as pd

In [7]:
stock_price_list = [10000,10350,10100,9600,10500,11350]
stock_price_Series = pd.Series([10000,10350,10100,9600,10500,11350])

stock_price_Series

0    10000
1    10350
2    10100
3     9600
4    10500
5    11350
dtype: int64

In [8]:
stock_price_list[1]
stock_price_list[1:3]

[10350, 10100]

In [9]:
stock_price_Series[1]
stock_price_Series[1:3]

1    10350
2    10100
dtype: int64

In [10]:
stock_price_Series_withIndex = pd.Series([10000,10350,10100,9600,10500,11350],
    index = ["2016-03-01","2016-03-02","2016-03-04","2016-03-05","2016-03-06","2016-03-07"])

In [11]:
stock_price_Series_withIndex

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
2016-03-06    10500
2016-03-07    11350
dtype: int64

In [19]:
stock_price_Series_withIndex["2016-03-04"]

10100

In [20]:
stock_price_Series_withIndex.index

Index(['2016-03-01', '2016-03-02', '2016-03-04', '2016-03-05', '2016-03-06',
       '2016-03-07'],
      dtype='object')

In [21]:
len(stock_price_Series_withIndex)

6

In [22]:
stock_price_Series_withIndex.values

array([10000, 10350, 10100,  9600, 10500, 11350], dtype=int64)

In [33]:
for i in range(0,len(stock_price_Series_withIndex)):
    print("Index : ",stock_price_Series_withIndex.index[i])
    print("values : ",stock_price_Series_withIndex.values[i])

Index :  2016-03-01
values :  10000
Index :  2016-03-02
values :  10350
Index :  2016-03-04
values :  10100
Index :  2016-03-05
values :  9600
Index :  2016-03-06
values :  10500
Index :  2016-03-07
values :  11350


In [29]:
for idx, value in enumerate(stock_price_Series_withIndex):
    print(idx)
    print(value)

0
10000
1
10350
2
10100
3
9600
4
10500
5
11350


In [32]:
for i in range(0,len(stock_price_Series_withIndex)):
    print(stock_price_Series_withIndex.index[i])
    print(stock_price_Series_withIndex.values[i])

2016-03-01
10000
2016-03-02
10350
2016-03-04
10100
2016-03-05
9600
2016-03-06
10500
2016-03-07
11350


In [34]:
for i in stock_price_Series_withIndex.index:
    print(i)
    print(stock_price_Series_withIndex[i])

2016-03-01
10000
2016-03-02
10350
2016-03-04
10100
2016-03-05
9600
2016-03-06
10500
2016-03-07
11350


In [35]:
stock_price_Series_withIndex[[0,3]]

2016-03-01    10000
2016-03-05     9600
dtype: int64

In [36]:
stock_price_Series_withIndex[["2016-03-02","2016-03-06"]]

2016-03-02    10350
2016-03-06    10500
dtype: int64

In [37]:
stock_price_list[0]

10000

In [38]:
stock_price_list[0:3]

[10000, 10350, 10100]

In [39]:
stock_price_list[[3,5]]

TypeError: list indices must be integers or slices, not list

In [40]:
search_index = [3,5]
[stock_price_list[i] for i in search_index]

[9600, 11350]

In [41]:
stock_price_Series_withIndex*2

2016-03-01    20000
2016-03-02    20700
2016-03-04    20200
2016-03-05    19200
2016-03-06    21000
2016-03-07    22700
dtype: int64

In [42]:
stock_price_Series_withIndex>10500

2016-03-01    False
2016-03-02    False
2016-03-04    False
2016-03-05    False
2016-03-06    False
2016-03-07     True
dtype: bool

In [43]:
stock_price_Series_withIndex[stock_price_Series_withIndex>10500]

2016-03-07    11350
dtype: int64

In [47]:
print(stock_price_Series_withIndex)
print("_____________________")
print("2016-03-05" in stock_price_Series_withIndex)

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
2016-03-06    10500
2016-03-07    11350
dtype: int64
_____________________
True


In [45]:
9600 in stock_price_Series_withIndex

False

In [46]:
"2016-03-5" in stock_price_Series_withIndex

False

In [52]:
sdata = {"APPLE":5000, "MS":2000, "AMAZON":4500}
obj3 = pd.Series(sdata)
print(obj3)

APPLE     5000
MS        2000
AMAZON    4500
dtype: int64


In [53]:
states = ["GOOGLE", "APPLE", "AMAZON"]
obj4 = pd.Series(sdata, states)
print(obj4)

GOOGLE       NaN
APPLE     5000.0
AMAZON    4500.0
dtype: float64


In [54]:
print(obj3 + obj4)
print(obj3 - obj4)

AMAZON     9000.0
APPLE     10000.0
GOOGLE        NaN
MS            NaN
dtype: float64
AMAZON    0.0
APPLE     0.0
GOOGLE    NaN
MS        NaN
dtype: float64


In [56]:
stock_price_Series_withIndex.iat[0]

10000

In [57]:
stock_price_Series_withIndex.at["2016-03-01"]

10000

In [65]:
print(stock_price_Series_withIndex.iloc[0:3])
print()
print(stock_price_Series_withIndex.iloc[[0,3]])

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
dtype: int64

2016-03-01    10000
2016-03-05     9600
dtype: int64


In [63]:
print(stock_price_Series_withIndex.loc["2016-03-01":"2016-03-05"])
print()
print(stock_price_Series_withIndex.loc[["2016-03-01","2016-03-05"]])

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
dtype: int64

2016-03-01    10000
2016-03-05     9600
dtype: int64


In [67]:
print(stock_price_Series_withIndex.count())
print(len(stock_price_Series_withIndex))

6
6


In [68]:
add_data = pd.Series([12100], index=["2016-03-08"])
print(stock_price_Series_withIndex.append(add_data))
print(stock_price_Series_withIndex)

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
2016-03-06    10500
2016-03-07    11350
2016-03-08    12100
dtype: int64
2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
2016-03-06    10500
2016-03-07    11350
dtype: int64


In [76]:
add_data = pd.Series([10000], index=["2016-03-05"])
print(stock_price_Series_withIndex.append(add_data, verify_integrity=True))  #verify_integrity=True -> 중복값이 있을 경우 넣을 수 없다
print(stock_price_Series_withIndex)

ValueError: Indexes have overlapping values: Index(['2016-03-05'], dtype='object')

In [101]:
d = [0,1,2,3,4]
df = pd.DataFrame(d)
print(df)
print()
ds = pd.Series(d)
print(ds)

   0
0  0
1  1
2  2
3  3
4  4

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [102]:
df.columns = ["column1"]
print(df)

   column1
0        0
1        1
2        2
3        3
4        4


In [103]:
df["newCol"] = d
print(df)
print()
df["newCol2"] = 5
print(df)

   column1  newCol
0        0       0
1        1       1
2        2       2
3        3       3
4        4       4

   column1  newCol  newCol2
0        0       0        5
1        1       1        5
2        2       2        5
3        3       3        5
4        4       4        5


In [104]:
df["newCol3"] = df.newCol2
print(df)

df["newCol3"] = df.newCol3 * 100
print(df)

   column1  newCol  newCol2  newCol3
0        0       0        5        5
1        1       1        5        5
2        2       2        5        5
3        3       3        5        5
4        4       4        5        5
   column1  newCol  newCol2  newCol3
0        0       0        5      500
1        1       1        5      500
2        2       2        5      500
3        3       3        5      500
4        4       4        5      500


In [105]:
print(df.iloc[1,2])

df.iloc[1,2] = 2000
print(df)

5
   column1  newCol  newCol2  newCol3
0        0       0        5      500
1        1       1     2000      500
2        2       2        5      500
3        3       3        5      500
4        4       4        5      500


In [106]:
print(df)

del df["column1"]
print(df)

   column1  newCol  newCol2  newCol3
0        0       0        5      500
1        1       1     2000      500
2        2       2        5      500
3        3       3        5      500
4        4       4        5      500
   newCol  newCol2  newCol3
0       0        5      500
1       1     2000      500
2       2        5      500
3       3        5      500
4       4        5      500


In [112]:
print(df.columns.values)
newColList = ['newCol2', 'newCol3']
df[newColList]

['newCol' 'newCol2' 'newCol3']


newCol2  newCol3
0        5      500
1     2000      500
2        5      500
3        5      500
4        5      500

In [13]:
stock_price_DF_withIndex = pd.DataFrame([10000,10350,10100,9600,10500,11350],
    index = ["2016-03-01","2016-03-02","2016-03-04","2016-03-05","2016-03-06","2016-03-07"])

stock_price_DF_withIndex

0
2016-03-01  10000
2016-03-02  10350
2016-03-04  10100
2016-03-05   9600
2016-03-06  10500
2016-03-07  11350

In [15]:
stock_price_DF_withIndex.rename(columns={"0":"시가"}, inplace = True)
stock_price_DF_withIndex

0
2016-03-01  10000
2016-03-02  10350
2016-03-04  10100
2016-03-05   9600
2016-03-06  10500
2016-03-07  11350

In [16]:
stock_price_DF_withIndex.rename(columns={0:"시가"}, inplace = True)
stock_price_DF_withIndex

시가
2016-03-01  10000
2016-03-02  10350
2016-03-04  10100
2016-03-05   9600
2016-03-06  10500
2016-03-07  11350

In [17]:
stock_price_DF_withIndex["종가"] = [11000, 12000, 10000, 13000, 12000, 11000]
stock_price_DF_withIndex["고가"] = [12000, 12500, 10800, 13000, 12900, 11700]
stock_price_DF_withIndex["저가"] = [10000, 10000, 9500, 11500, 11000, 9900]
stock_price_DF_withIndex

시가     종가     고가     저가
2016-03-01  10000  11000  12000  10000
2016-03-02  10350  12000  12500  10000
2016-03-04  10100  10000  10800   9500
2016-03-05   9600  13000  13000  11500
2016-03-06  10500  12000  12900  11000
2016-03-07  11350  11000  11700   9900

In [18]:
stock_price_DF_withIndex.iat[0] # 2차원 데이터이기 때문에 오류발생

TypeError: _get_value() missing 1 required positional argument: 'col'

In [19]:
stock_price_DF_withIndex.iat[0,3]

10000

In [20]:
stock_price_DF_withIndex.loc["2016-03-01",["시가","종가"]]

시가    10000
종가    11000
Name: 2016-03-01, dtype: int64

In [21]:
stock_price_DF_withIndex.loc["2016-03-01":"2016-03-04", ]

시가     종가     고가     저가
2016-03-01  10000  11000  12000  10000
2016-03-02  10350  12000  12500  10000
2016-03-04  10100  10000  10800   9500

In [22]:
stock_price_DF_withIndex.values

array([[10000, 11000, 12000, 10000],
       [10350, 12000, 12500, 10000],
       [10100, 10000, 10800,  9500],
       [ 9600, 13000, 13000, 11500],
       [10500, 12000, 12900, 11000],
       [11350, 11000, 11700,  9900]], dtype=int64)

In [23]:
stock_price_DF_withIndex.shape

(6, 4)

In [24]:
stock_price_DF_withIndex.shape[1]

4

In [25]:
stock_price_DF_withIndex.size

24

In [26]:
stock_price_DF_withIndex.ndim

2

In [27]:
obj = pd.Series([4.5,7.2,-5.3], index=["c","b","a"])
obj

c    4.5
b    7.2
a   -5.3
dtype: float64

In [28]:
obj2 = obj.reindex(["a","b","c","d","e"])
obj2

a   -5.3
b    7.2
c    4.5
d    NaN
e    NaN
dtype: float64

In [29]:
obj.reindex(["a","b"])

a   -5.3
b    7.2
dtype: float64

In [30]:
obj.reindex(["a","b","c","d","e"], fill_value=0)

a   -5.3
b    7.2
c    4.5
d    0.0
e    0.0
dtype: float64

In [31]:
# 보간법
obj = pd.Series([4.5,7.2,-5.3], index=["c","b","a"])
print(obj)
print("---------------")
print(obj.reindex(["a","d","e","c","b"]))
print("---------------")
print(obj.reindex(["a","d","e","c","b"]).interpolate())

c    4.5
b    7.2
a   -5.3
dtype: float64
---------------
a   -5.3
d    NaN
e    NaN
c    4.5
b    7.2
dtype: float64
---------------
a   -5.300000
d   -2.033333
e    1.233333
c    4.500000
b    7.200000
dtype: float64


In [32]:
df = pd.DataFrame([4.5,7.2,-5.3], index=["c","b","a"])
df = df.reindex(["a","d","e","c","b"])
print(df)
print("---------------")
df["interPo"] = df.iloc[:,0].interpolate()
print(df)

     0
a -5.3
d  NaN
e  NaN
c  4.5
b  7.2
---------------
     0   interPo
a -5.3 -5.300000
d  NaN -2.033333
e  NaN  1.233333
c  4.5  4.500000
b  7.2  7.200000


## DataFrame / Series - apply & lambda (일괄 적용)<br>
### 일괄적용 : 줄단위 - apply / 각 셀 - applymap<br>
#### (가로줄/세로줄 = axis=0/1로 적용)

In [33]:
# 일별로 가장 큰값, 가장 작은값 찾아서 차이 계산
stock_price_DF_withIndex.apply(lambda x : x.max() - x.min(), axis = 1)

2016-03-01    2000
2016-03-02    2500
2016-03-04    1300
2016-03-05    3400
2016-03-06    2400
2016-03-07    1800
dtype: int64

### 기준을 가로 / 세로 등으로 해보기 & 값들을 더하거나 곱하는 것들로 일괄 변경!

In [34]:
print(stock_price_DF_withIndex.apply(lambda x : x.max() - x.min(), axis = 0))
print("======================================================")
print(stock_price_DF_withIndex.apply(lambda x : x.max() - x.min(), axis = 1))
print("======================================================")
print(stock_price_DF_withIndex.apply(lambda x : x + 1))
print("======================================================")
print(stock_price_DF_withIndex.apply(lambda x : x*100 ))

시가    1750
종가    3000
고가    2200
저가    2000
dtype: int64
2016-03-01    2000
2016-03-02    2500
2016-03-04    1300
2016-03-05    3400
2016-03-06    2400
2016-03-07    1800
dtype: int64
               시가     종가     고가     저가
2016-03-01  10001  11001  12001  10001
2016-03-02  10351  12001  12501  10001
2016-03-04  10101  10001  10801   9501
2016-03-05   9601  13001  13001  11501
2016-03-06  10501  12001  12901  11001
2016-03-07  11351  11001  11701   9901
                 시가       종가       고가       저가
2016-03-01  1000000  1100000  1200000  1000000
2016-03-02  1035000  1200000  1250000  1000000
2016-03-04  1010000  1000000  1080000   950000
2016-03-05   960000  1300000  1300000  1150000
2016-03-06  1050000  1200000  1290000  1100000
2016-03-07  1135000  1100000  1170000   990000


### Q) stock_price_DF_withIndex에서 "Gap"이란 컬럼을 생성하고, 시가/종가/고가/저가 중에서 가장 큰 값과 가장 작은 값의 차이를 기록하는 컬럼을 생성하시오

In [35]:
gap = stock_price_DF_withIndex.apply(lambda x : x.max() - x.min(), axis = 1)
stock_price_DF_withIndex["Gap"] = gap
stock_price_DF_withIndex

시가     종가     고가     저가   Gap
2016-03-01  10000  11000  12000  10000  2000
2016-03-02  10350  12000  12500  10000  2500
2016-03-04  10100  10000  10800   9500  1300
2016-03-05   9600  13000  13000  11500  3400
2016-03-06  10500  12000  12900  11000  2400
2016-03-07  11350  11000  11700   9900  1800

### Q) For loop으로 만들어보기

In [36]:
stock_price_DF_withIndex["Gap_forloop"] = 0
for i in range(0,len(stock_price_DF_withIndex)) :
    maxi = stock_price_DF_withIndex.iloc[i, :4].max()
    mini = stock_price_DF_withIndex.iloc[i, :4].min()
    gap =  maxi - mini
    stock_price_DF_withIndex["Gap_forloop"][i] = gap

stock_price_DF_withIndex

시가     종가     고가     저가   Gap  Gap_forloop
2016-03-01  10000  11000  12000  10000  2000         2000
2016-03-02  10350  12000  12500  10000  2500         2500
2016-03-04  10100  10000  10800   9500  1300         1300
2016-03-05   9600  13000  13000  11500  3400         3400
2016-03-06  10500  12000  12900  11000  2400         2400
2016-03-07  11350  11000  11700   9900  1800         1800

In [37]:
stock_price_DF_withIndex["Gap_forloop_test"] = 0
labels = ["Gap_forloop_test"]
index_ints = [stock_price_DF_withIndex.columns.get_loc(label) for label in labels]
index_ints # 컬럼의 위치파악

for i in range(0,len(stock_price_DF_withIndex)) :
    tempValue = stock_price_DF_withIndex.iloc[i,0:4]
    tempMax = tempValue.max()
    tempMin = tempValue.min()
    stock_price_DF_withIndex.iloc[i,index_ints[0]] = tempMax - tempMin
    
stock_price_DF_withIndex

시가     종가     고가     저가   Gap  Gap_forloop  Gap_forloop_test
2016-03-01  10000  11000  12000  10000  2000         2000              2000
2016-03-02  10350  12000  12500  10000  2500         2500              2500
2016-03-04  10100  10000  10800   9500  1300         1300              1300
2016-03-05   9600  13000  13000  11500  3400         3400              3400
2016-03-06  10500  12000  12900  11000  2400         2400              2400
2016-03-07  11350  11000  11700   9900  1800         1800              1800

### Q) 3/1 ~ 5일까지의 "시가"~"저가"까지 평균을 구해라

In [38]:
print(stock_price_DF_withIndex[["시가", "종가", "고가", "저가"]].apply(lambda x : np.mean(x), axis = 1))
# np.mean(x) 도 가능

# 시가 ~ 저가 별 평균
print(stock_price_DF_withIndex[["시가", "종가", "고가", "저가"]].apply(lambda x : x.mean(), axis = 0))

2016-03-01    10750.0
2016-03-02    11212.5
2016-03-04    10100.0
2016-03-05    11775.0
2016-03-06    11600.0
2016-03-07    10987.5
dtype: float64
시가    10316.666667
종가    11500.000000
고가    12150.000000
저가    10316.666667
dtype: float64


### DATA Cleaning <br>
- 유일한값 찾기 : .unique()
- 결측치 처리 : dropna(), fillna()...

In [39]:
### Data Cleaning
from numpy import nan as NA
import pandas as pd
data = pd.DataFrame([[1,6.5,3],[1,NA,NA],[NA,NA,NA],[NA,6.5,3]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [40]:
cleanded = data.dropna() # 가로줄 기준 처리 => 세로줄 : axis = 1
cleanded

0    1    2
0  1.0  6.5  3.0

In [41]:
print(data.dropna(how="all", axis=0)) # 가로줄 기준 모든 값이 결측치일 때 제거.

print(data.dropna(how="all", axis=1))

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0


In [42]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0 -0.672283       NaN       NaN
1  0.199706       NaN       NaN
2 -0.792185       NaN  0.623789
3  0.759822       NaN -0.106440
4  0.137731  1.366380  0.333087
5 -0.553494 -0.614551  0.294662
6  0.733857 -0.921901 -0.718581

In [43]:
df.dropna()

0         1         2
4  0.137731  1.366380  0.333087
5 -0.553494 -0.614551  0.294662
6  0.733857 -0.921901 -0.718581

In [44]:
df.dropna(thresh=2) # 가로줄 기준으로 2개 이상의 정상값이 있으면 살려둔다

0         1         2
2 -0.792185       NaN  0.623789
3  0.759822       NaN -0.106440
4  0.137731  1.366380  0.333087
5 -0.553494 -0.614551  0.294662
6  0.733857 -0.921901 -0.718581

In [45]:
# 1칼럼은 9999로, 3칼럼은 -9999로 처리
# 단, 3칼럼은 없으니 에러 및 경고없이 처리가 됨에 유의!
df.fillna({1:9999, 3:-9999})

0            1         2
0 -0.672283  9999.000000       NaN
1  0.199706  9999.000000       NaN
2 -0.792185  9999.000000  0.623789
3  0.759822  9999.000000 -0.106440
4  0.137731     1.366380  0.333087
5 -0.553494    -0.614551  0.294662
6  0.733857    -0.921901 -0.718581

### IO from pandas

In [49]:
import pandas as pd
testCSV_path="C:\\Users\\acorn\\Jupyter\\sampledata\\01_olive.csv"

olive_oil = pd.read_csv(testCSV_path)
olive_oil.head(10)

Unnamed: 0  region  area  palmitic  palmitoleic  stearic  oleic  \
0   1.North-Apulia       1     1      1075           75      226   7823   
1   2.North-Apulia       1     1      1088           73      224   7709   
2   3.North-Apulia       1     1       911           54      246   8113   
3   4.North-Apulia       1     1       966           57      240   7952   
4   5.North-Apulia       1     1      1051           67      259   7771   
5   6.North-Apulia       1     1       911           49      268   7924   
6   7.North-Apulia       1     1       922           66      264   7990   
7   8.North-Apulia       1     1      1100           61      235   7728   
8   9.North-Apulia       1     1      1082           60      239   7745   
9  10.North-Apulia       1     1      1037           55      213   7944   

   linoleic  linolenic  arachidic  eicosenoic  
0       672         36         60          29  
1       781         31         61          29  
2       549         31         63          29  
3       619         50         78          35  
4       672         50         80          46  
5       678         51         70          44  
6       618         49         56          29  
7       734         39         64          35  
8       709         46         83          33  
9       633         26         52          30

In [50]:
olive_oil = pd.read_csv(testCSV_path, header=None)
olive_oil.head(3)

0       1     2         3            4        5      6   \
0             NaN  region  area  palmitic  palmitoleic  stearic  oleic   
1  1.North-Apulia       1     1      1075           75      226   7823   
2  2.North-Apulia       1     1      1088           73      224   7709   

         7          8          9           10  
0  linoleic  linolenic  arachidic  eicosenoic  
1       672         36         60          29  
2       781         31         61          29

In [51]:
olive_oil = pd.read_csv(testCSV_path, names=["a","b","c","d"])
olive_oil.head(3) # 뒷쪽부터 채움

a  \
NaN            region area palmitic palmitoleic stearic oleic  linoleic   
1.North-Apulia 1      1    1075     75          226     7823        672   
2.North-Apulia 1      1    1088     73          224     7709        781   

                                                                       b  \
NaN            region area palmitic palmitoleic stearic oleic  linolenic   
1.North-Apulia 1      1    1075     75          226     7823          36   
2.North-Apulia 1      1    1088     73          224     7709          31   

                                                                       c  \
NaN            region area palmitic palmitoleic stearic oleic  arachidic   
1.North-Apulia 1      1    1075     75          226     7823          60   
2.North-Apulia 1      1    1088     73          224     7709          61   

                                                                        d  
NaN            region area palmitic palmitoleic stearic oleic  eicosenoic  
1.North-Apulia 1      1    1075     75          226     7823           29  
2.North-Apulia 1      1    1088     73          224     7709           29

In [52]:
olive_oil = pd.read_csv(testCSV_path, skiprows=1)
olive_oil.head(3) # 첫번째 컬럼을 skip함

1.North-Apulia  1  1.1  1075  75  226  7823  672  36  60  29
0  2.North-Apulia  1    1  1088  73  224  7709  781  31  61  29
1  3.North-Apulia  1    1   911  54  246  8113  549  31  63  29
2  4.North-Apulia  1    1   966  57  240  7952  619  50  78  35

In [53]:
olive_oil = pd.read_csv(testCSV_path)
olive_oil.rename(columns={"Unnamed: 0" : "id_area"}, inplace = True )
olive_oil.rename(columns={olive_oil.columns[0] : "id_area"}, inplace = True )
olive_oil.head(3)

id_area  region  area  palmitic  palmitoleic  stearic  oleic  \
0  1.North-Apulia       1     1      1075           75      226   7823   
1  2.North-Apulia       1     1      1088           73      224   7709   
2  3.North-Apulia       1     1       911           54      246   8113   

   linoleic  linolenic  arachidic  eicosenoic  
0       672         36         60          29  
1       781         31         61          29  
2       549         31         63          29

- 주어진 데이터의 id로 활용할 칼럼의 값이 유니크한지 확인 -> 제일 중요!
- python은 중복 인덱스가 가능하기 때문에

In [54]:
len(olive_oil["id_area"].unique()) == olive_oil.shape[0] # OR len(olive_oil)

True

In [55]:
olive_oil["id_area"][0].split(".")

['1', 'North-Apulia']

In [56]:
olive_oil["id_area"][0].split(".")[0]

'1'

In [57]:
int(olive_oil["id_area"][0].split(".")[0]) - 1

0

In [58]:
ss = str(int(olive_oil["id_area"][0].split(".")[0]) - 1)
print(ss)

0


In [59]:
print(ss + "_" + olive_oil["id_area"][0].split(".")[1])
print(str(int(olive_oil["id_area"][1].split(".")[0]) - 1) + "_" + olive_oil["id_area"][1].split(".")[1])

0_North-Apulia
1_North-Apulia


In [60]:

area = olive_oil["id_area"].apply(lambda x : str(int(x.split(".")[0]) - 1) 
                               + "_" + x.split(".")[1])
olive_oil["id_area"] = area
olive_oil.head(3)

id_area  region  area  palmitic  palmitoleic  stearic  oleic  \
0  0_North-Apulia       1     1      1075           75      226   7823   
1  1_North-Apulia       1     1      1088           73      224   7709   
2  2_North-Apulia       1     1       911           54      246   8113   

   linoleic  linolenic  arachidic  eicosenoic  
0       672         36         60          29  
1       781         31         61          29  
2       549         31         63          29

### Q) palmitoleic 칼럼 값을 100으로 나누어서 소수로 표시하시오. apply/lambda 사용하기.

In [61]:
olive_oil["palmitoleic"] = olive_oil["palmitoleic"].apply(lambda x : x/100)
olive_oil.head(3)

id_area  region  area  palmitic  palmitoleic  stearic  oleic  \
0  0_North-Apulia       1     1      1075         0.75      226   7823   
1  1_North-Apulia       1     1      1088         0.73      224   7709   
2  2_North-Apulia       1     1       911         0.54      246   8113   

   linoleic  linolenic  arachidic  eicosenoic  
0       672         36         60          29  
1       781         31         61          29  
2       549         31         63          29

### 처리한 파일을 외부파일로 출력하기! to_~

In [62]:
olive_oil.to_csv("olive2.csv") # 경로 지정안할시 파이썬파일 실행되는 곳으로 저장

### 구분자가 다를때 읽어들이는 법

In [63]:
### @으로 구분된 csv 파일 읽기
### 00) 파일 경로
sur_at = pd.read_csv("C:\\Users\\acorn\\Jupyter\\sampledata\\03_surveys_withAt.csv")
sur_at = pd.read_csv("C:\\Users\\acorn\\Jupyter\\sampledata\\03_surveys_withAt.csv"
                     , sep=",")
sur_at.head(3)

record_id@month@day@year@plot_id@species_id@sex@hindfoot_length@weight
0                             1@7@16@1977@2@NL@M@32@                    
1                             2@7@16@1977@3@NL@M@33@                    
2                             3@7@16@1977@2@DM@F@37@

In [64]:
sur_at = pd.read_csv("C:\\Users\\acorn\\Jupyter\\sampledata\\03_surveys_withAt.csv"
                     , sep="@")
sur_at.head(3)

record_id  month  day  year  plot_id species_id sex  hindfoot_length  \
0          1      7   16  1977        2         NL   M             32.0   
1          2      7   16  1977        3         NL   M             33.0   
2          3      7   16  1977        2         DM   F             37.0   

   weight  
0     NaN  
1     NaN  
2     NaN

### 동일한 형식의 여러 파일을 일괄적으로 읽어보자!
- 위의 작업을 하기 위해서는 몇 가지 사항을 확인해야 함

In [65]:
# 기본적으로 glob에 관련된 내용 확인.
# 실제 glob.glob를 통해서 받은 결과가 무엇인지 확인!->경로에 관한 리스트로 받게 됨.
import glob
import sys
import os

In [66]:
many_file_path = "C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\*.csv"
filePathList = glob.glob(many_file_path)

print(filePathList)

['C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1763.csv', 'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1764.csv', 'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1765.csv', 'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1766.csv', 'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1767.csv', 'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1768.csv', 'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1769.csv', 'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1770.csv', 'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1771.csv', 'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1772.csv']


In [67]:
filePathList[2]

'C:\\Users\\acorn\\Jupyter\\sampledata\\06_manyfile\\1765.csv'

In [68]:
"data_" + os.path.basename(filePathList[2]).split(".")[0]

'data_1765'

In [69]:
for i in range(0,len(filePathList)):
    temp = os.path.basename(filePathList[i])
    temp = os.path.splitext(temp)[0]
    vars()["data_" + str(temp)] = pd.read_csv(filePathList[i])
    # 문자열을 변수명으로 바꿔주는 역할
    
data_1763.head(3)

ITE00100554  17630101  TMAX  -36  Unnamed: 4 Unnamed: 5  E  Unnamed: 7
0  ITE00100554  17630101  TMIN  -50         NaN        NaN  E         NaN
1  ITE00100554  17630102  TMAX  -26         NaN        NaN  E         NaN
2  ITE00100554  17630102  TMIN  -40         NaN        NaN  E         NaN

In [70]:
# Excel 파일 읽고 쓰기
# 01) 엑셀 파일 읽기
excelInPath = "C:\\Users\\acorn\\Jupyter\\sampledata\\07_surveys_excelformat.xls"

excel_data= pd.read_excel(excelInPath, sheet_name = "Sheet1")
excel_data.head(3)

record_id  month  day  year  plot_id species_id sex  hindfoot_length  \
0          1      7   16  1977        2         NL   M             32.0   
1          2      7   16  1977        3         NL   M             33.0   
2          3      7   16  1977        2         DM   F             37.0   

   weight  
0     NaN  
1     NaN  
2     NaN

In [71]:
excel_data = excel_data.fillna(0)
print(excel_data.head(3))

# 엑셀파일로 내보내기
excel_data.to_excel("dddd.xlsx")

   record_id  month  day  year  plot_id species_id sex  hindfoot_length  \
0          1      7   16  1977        2         NL   M             32.0   
1          2      7   16  1977        3         NL   M             33.0   
2          3      7   16  1977        2         DM   F             37.0   

   weight  
0     0.0  
1     0.0  
2     0.0  


In [72]:
########### JSON #########
# 00) JSON Init / Packages import
import pandas as pd
import json

- 연습1)

In [78]:
# 01) json 만들기
json_data1 = """{
    "color": "red",
    "value": "#f00"
}"""

result = json.loads(json_data1)
print (result)

{'color': 'red', 'value': '#f00'}


In [79]:
result["value"]

'#f00'

In [80]:
# 02) json data2
json_data2 = """{
    "id": "0001",
    "type": "donut",
    "name": "Cake",
    "ppu": 0.55,
    "batters":{
            "batter": [
                            { "id": "1001", "type": "Regular" },
                            { "id": "1002", "type": "Chocolate" },
                            { "id": "1003", "type": "Blueberry" },
                            { "id": "1004", "type": "Devil's Food" }
                            ]
                        },
    "topping":
        [
            { "id": "5001", "type": "None" },
            { "id": "5002", "type": "Glazed" },
            { "id": "5005", "type": "Sugar" },
            { "id": "5007", "type": "Powdered Sugar" },
            { "id": "5006", "type": "Chocolate with Sprinkles" },
            { "id": "5003", "type": "Chocolate" },
            { "id": "5004", "type": "Maple" }
]
}"""
result = json.loads(json_data2)
print (result)

{'id': '0001', 'type': 'donut', 'name': 'Cake', 'ppu': 0.55, 'batters': {'batter': [{'id': '1001', 'type': 'Regular'}, {'id': '1002', 'type': 'Chocolate'}, {'id': '1003', 'type': 'Blueberry'}, {'id': '1004', 'type': "Devil's Food"}]}, 'topping': [{'id': '5001', 'type': 'None'}, {'id': '5002', 'type': 'Glazed'}, {'id': '5005', 'type': 'Sugar'}, {'id': '5007', 'type': 'Powdered Sugar'}, {'id': '5006', 'type': 'Chocolate with Sprinkles'}, {'id': '5003', 'type': 'Chocolate'}, {'id': '5004', 'type': 'Maple'}]}


In [81]:
result["topping"][2]["type"]

'Sugar'

In [82]:
print(result["batter"]) # 바로 접근은 못한다.


KeyError: 'batter'

### Q) 앞의 데이터에서 batter 2번째 id값을 출력하라, 2번째 topping의 데이터를 출력하라

In [83]:
print(result)
print(result["batters"]["batter"][1]["id"])

{'id': '0001', 'type': 'donut', 'name': 'Cake', 'ppu': 0.55, 'batters': {'batter': [{'id': '1001', 'type': 'Regular'}, {'id': '1002', 'type': 'Chocolate'}, {'id': '1003', 'type': 'Blueberry'}, {'id': '1004', 'type': "Devil's Food"}]}, 'topping': [{'id': '5001', 'type': 'None'}, {'id': '5002', 'type': 'Glazed'}, {'id': '5005', 'type': 'Sugar'}, {'id': '5007', 'type': 'Powdered Sugar'}, {'id': '5006', 'type': 'Chocolate with Sprinkles'}, {'id': '5003', 'type': 'Chocolate'}, {'id': '5004', 'type': 'Maple'}]}
1002


In [84]:
print(result["topping"][1])

{'id': '5002', 'type': 'Glazed'}


### 참고) 아래는 python 3 기준, pandas 20이상, anaconda 기준

In [197]:
### KOBIS 데이터 실습 ####
# 01) Packages
import pandas as pd
import urllib.request
import json

# 02) JOSN Format : 2016 Open & 20item/perPage
movieIdListURL = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieList.json?key=675f83ad573ce1afad60b604dd62e6b4&openStartDt=2020&itemPerPage=40"
movieIdPage = urllib.request.urlopen(movieIdListURL)


movieIdData = json.loads(movieIdPage.read().decode('utf8'),encoding='utf-8')
# utf-8, utf8 둘다 가능
movieIdData


{'movieListResult': {'totCnt': 79,
  'source': '영화진흥위원회',
  'movieList': [{'movieCd': '20190009',
    'movieNm': '카잔자키스',
    'movieNmEn': 'Kazantzakis',
    'prdtYear': '2018',
    'openDt': '20200130',
    'typeNm': '장편',
    'prdtStatNm': '개봉예정',
    'nationAlt': '기타',
    'genreAlt': '드라마',
    'repNationNm': '기타',
    'repGenreNm': '드라마',
    'directors': [],
    'companys': []},
   {'movieCd': '20183002',
    'movieNm': '해치지않아',
    'movieNmEn': 'SECRET ZOO',
    'prdtYear': '2019',
    'openDt': '20200115',
    'typeNm': '장편',
    'prdtStatNm': '개봉',
    'nationAlt': '한국',
    'genreAlt': '코미디',
    'repNationNm': '한국',
    'repGenreNm': '코미디',
    'directors': [{'peopleNm': '손재곤'}],
    'companys': [{'companyCd': '20100807', 'companyNm': '(주)디씨지플러스'},
     {'companyCd': '20140742', 'companyNm': '(주)어바웃필름'}]},
   {'movieCd': '20188421',
    'movieNm': '미스터 주: 사라진 VIP',
    'movieNmEn': 'MR. ZOO: THE MISSING VIP',
    'prdtYear': '2018',
    'openDt': '20200122',
    'typeNm': '장

In [96]:
len(movieIdData["movieListResult"]["movieList"])

40

In [98]:
print(movieIdData["movieListResult"]["movieList"][0]["movieCd"])
print(movieIdData["movieListResult"]["movieList"][0]["movieNm"])
print(movieIdData["movieListResult"]["movieList"][0]["movieNmEn"])
print(movieIdData["movieListResult"]["movieList"][0]["openDt"])
print(movieIdData["movieListResult"]["movieList"][0]["typeNm"])
print(movieIdData["movieListResult"]["movieList"][0]["directors"][0]["peopleNm"])

20183002
해치지않아
SECRET ZOO
20200115
장편
손재곤


In [105]:

movieLen = movieIdData["movieListResult"]["movieList"]

for i in range(0, len(movieLen)):
    print("Code : " + movieLen[i]["movieCd"])
    print("Movie : " + movieLen[i]["movieNm"])
    print("MovieEn : " + movieLen[i]["movieNmEn"])
    print("openDate : " + movieLen[i]["openDt"])
    if movieLen[i]["directors"] == [] :
        print("Unknown")
    else :
        print("Director : " + movieLen[i]["directors"][0]["peopleNm"])
   

Code : 20183002
Movie : 해치지않아
MovieEn : SECRET ZOO
openDate : 20200115
Director : 손재곤
Code : 20188421
Movie : 미스터 주: 사라진 VIP
MovieEn : MR. ZOO: THE MISSING VIP
openDate : 20200122
Director : 김태윤
Code : 20192101
Movie : 히트맨
MovieEn : HITMAN: AGENT JUN
openDate : 20200122
Director : 최원섭
Code : 20180939
Movie : 남산의 부장들
MovieEn : The Man Standing Next
openDate : 20200122
Director : 우민호
Code : 20196674
Movie : 갱
MovieEn : GANG
openDate : 20200116
Director : 조바른
Code : 20192604
Movie : 오즈의 마법사: 요술구두와 말하는 책
MovieEn : Fantastic Return to OZ
openDate : 20200122
Unknown
Code : 20193478
Movie : 브라 이야기
MovieEn : The Bra
openDate : 20200116
Director : 바이트 헬머
Code : 20192240
Movie : 작은 아씨들
MovieEn : Little Women
openDate : 20200212
Director : 그레타 거윅
Code : 20191682
Movie : 몽마르트 파파
MovieEn : Montmartre de Papa
openDate : 20200109
Director : 민병우
Code : 20194975
Movie : 소녀가 소녀에게
MovieEn : Girls Encounter
openDate : 20200109
Director : 에다 유카
Code : 20196670
Movie : 나쁜 녀석들: 포에버
MovieEn : Bad Boys for Lif

In [198]:
movieIDDF = pd.DataFrame()
movieIDDF_temp = pd.DataFrame()
movieIDDF_temp = movieIDDF_temp.append({"movieCd":"", "movieNm":"", "movieNmEn":"", "openDt":"", "directorpeopleNm":""}, ignore_index=True)
movieLen = movieIdData["movieListResult"]["movieList"]
# ignore_index = True : 합친 부분들 정렬

for i in range(0, len(movieLen)):
    # 데이터 담기
    movieIDDF_temp["movieCd"] = movieLen[i]["movieCd"]
    movieIDDF_temp["movieNm"] = movieLen[i]["movieNm"]
    movieIDDF_temp["movieNmEn"] = movieLen[i]["movieNmEn"]
    movieIDDF_temp["openDt"] = movieLen[i]["openDt"]
    if movieLen[i]["directors"] == [] :
        movieIDDF_temp["directorpeopleNm"] = "Unknown"
    else :
        movieIDDF_temp["directorpeopleNm"] = movieLen[i]["directors"][0]["peopleNm"]
    
    # 합치기
    movieIDDF = movieIDDF.append(movieIDDF_temp, ignore_index = True)
    
    # 비우기
    movieIDDF_temp = pd.DataFrame()
    movieIDDF_temp = movieIDDF_temp.append({"movieCd":"", "movieNm":"", "movieNmEn":"", "openDt":"", "directorpeopleNm":""}, ignore_index=True)
    
movieIDDF




directorpeopleNm   movieCd               movieNm  \
0           Unknown  20190009                 카잔자키스   
1               손재곤  20183002                 해치지않아   
2               김태윤  20188421        미스터 주: 사라진 VIP   
3               최원섭  20192101                   히트맨   
4               우민호  20180939               남산의 부장들   
5               조바른  20196674                     갱   
6           Unknown  20192604  오즈의 마법사: 요술구두와 말하는 책   
7            바이트 헬머  20193478                브라 이야기   
8            그레타 거윅  20192240                작은 아씨들   
9               민병우  20191682               몽마르트 파파   
10            에다 유카  20194975              소녀가 소녀에게   
11         아딜 엘 아르비  20196670           나쁜 녀석들: 포에버   
12         프랑코 제피렐리  20193184               일 트로바토레   
13              최성은  20193393               어린 관리사    
14               조지  20197751       무림방주: 절대고수의 탄생    
15              신성진  20192507             도도녀 길들이기    
16          카와사키 군지  20204089       친구엄마들:세 친구의 스와핑   
17          줄리언 파리노  20191311              차일드 인 타임   
18              이민환  20193686      잠 못 이루는 섹스2 무삭제판   
19              강성옥  20190562     울지마 톤즈 2 : 슈크란 바바   
20              정진호  20190740               어린 처형 3   
21          카와사키 군지  20204090            애인:일본 유부녀들   
22         차야놉 분프라콥  20190851                   썩시드   
23              원명준  20193524                수상한동거    
24              나영창  20197972                  리틀 큐   
25          하라다 칸토나  20204060       나쁜 섹스:겁탈 당한 아내3   
26          카와사키 군지  20204101            꼬치집:과부 여주인   
27           셀린 시아마  20198676           타오르는 여인의 초상   
28          Unknown  20192370                  디어스킨   
29      스벤 운터발트 주니어  20196161            타발루가와 얼음공주   
30              천성준  20203922             아내의유혹-무삭제   
31           스티븐 개건  20199581                닥터 두리틀   
32       J.J. 에이브럼스  20195462    스타워즈: 라이즈 오브 스카이워커   
33        쥬세페 토르나토레  20124722             피아니스트의 전설   
34              장유정  20193321                정직한 후보   
35         미즈시마 츠토무  20196842       걸즈 앤 판처 최종장 제1화   
36          Unknown  20190770              어린 이모 3    
37              최재후  20191035                  무한정사   
38              김석만  20193691               스와핑 동창회   
39              최민현  20193870     데릴사위 : 젊은 장모를 탐하다   

                               movieNmEn    openDt  
0                            Kazantzakis  20200130  
1                             SECRET ZOO  20200115  
2               MR. ZOO: THE MISSING VIP  20200122  
3                      HITMAN: AGENT JUN  20200122  
4                  The Man Standing Next  20200122  
5                                   GANG  20200116  
6                 Fantastic Return to OZ  20200122  
7                                The Bra  20200116  
8                           Little Women  20200212  
9                     Montmartre de Papa  20200109  
10                       Girls Encounter  20200109  
11                     Bad Boys for Life  20200115  
12                          Il Trovatore  20200112  
13                                        20200110  
14                                        20200110  
15                                        20200110  
16                     SIN TOMONOHAHA 01  20200109  
17                     The Child in Time  20200109  
18                                        20200109  
19                                        20200109  
20                                        20200109  
21                       KYAKUTONERUTUMA  20200109  
22                              SUCKSEED  20200109  
23                                        20200109  
24                              Little Q  20200109  
25               OKASARETEMOWASURENAI-01  20200109  
26                KANASIMIYOKOTYOUNOONNA  20200109  
27            Portrait of a Lady on Fire  20200116  
28                              Deerskin  20200101  
29                              TABALUGA  20200108  
30                                        20200108  
31                              Dolittle  20200108 

In [199]:
movieIDDF["year"] = movieIDDF["openDt"].apply(lambda x : x[:4])
movieIDDF["month"] = movieIDDF["openDt"].apply(lambda x : x[4:6])
movieIDDF["day"] = movieIDDF["openDt"].apply(lambda x : x[6:])

In [126]:
movieIDDF

openDt  year month day               movieNm  \
movieCd                                                    
20192370  20200101  2020    01  01                  디어스킨   
20124722  20200101  2020    01  01             피아니스트의 전설   
20191035  20200102  2020    01  02                  무한정사   
20190770  20200102  2020    01  02              어린 이모 3    
20192392  20200106  2020    01  06             허락해버린 간호사   
20193870  20200106  2020    01  06     데릴사위 : 젊은 장모를 탐하다   
20193691  20200107  2020    01  07               스와핑 동창회   
20199581  20200108  2020    01  08                닥터 두리틀   
20203922  20200108  2020    01  08             아내의유혹-무삭제   
20195462  20200108  2020    01  08    스타워즈: 라이즈 오브 스카이워커   
20196161  20200108  2020    01  08            타발루가와 얼음공주   
20196842  20200108  2020    01  08       걸즈 앤 판처 최종장 제1화   
20191682  20200109  2020    01  09               몽마르트 파파   
20190740  20200109  2020    01  09               어린 처형 3   
20190562  20200109  2020    01  09     울지마 톤즈 2 : 슈크란 바바   
20204089  20200109  2020    01  09       친구엄마들:세 친구의 스와핑   
20191311  20200109  2020    01  09              차일드 인 타임   
20193524  20200109  2020    01  09                수상한동거    
20194975  20200109  2020    01  09              소녀가 소녀에게   
20204060  20200109  2020    01  09       나쁜 섹스:겁탈 당한 아내3   
20204101  20200109  2020    01  09            꼬치집:과부 여주인   
20204090  20200109  2020    01  09            애인:일본 유부녀들   
20190851  20200109  2020    01  09                   썩시드   
20197972  20200109  2020    01  09                  리틀 큐   
20193686  20200109  2020    01  09      잠 못 이루는 섹스2 무삭제판   
20197751  20200110  2020    01  10       무림방주: 절대고수의 탄생    
20193393  20200110  2020    01  10               어린 관리사    
20192507  20200110  2020    01  10             도도녀 길들이기    
20193184  20200112  2020    01  12               일 트로바토레   
20196670  20200115  2020    01  15           나쁜 녀석들: 포에버   
20183002  20200115  2020    01  15                 해치지않아   
20198676  20200116  2020    01  16           타오르는 여인의 초상   
20196674  20200116  2020    01  16                     갱   
20193478  20200116  2020    01  16                브라 이야기   
20192604  20200122  2020    01  22  오즈의 마법사: 요술구두와 말하는 책   
20180939  20200122  2020    01  22               남산의 부장들   
20192101  20200122  2020    01  22                   히트맨   
20188421  20200122  2020    01  22        미스터 주: 사라진 VIP   
20192240  20200212  2020    02  12                작은 아씨들   
20193321  20200212  2020    02  12                정직한 후보   

                                     movieNmEn directorpeopleNm  
movieCd                                                          
20192370                              Deerskin          Unknown  
20124722                    The Legend Of 1900        쥬세페 토르나토레  
20191035                                                    최재후  
20190770                                                Unknown  
20192392                    Kotsujiko-de Nyuin          Unknown  
20193870                                                    최민현  
20193691                                                    김석만  
20199581                              Dolittle           스티븐 개건  
20203922                                                    천성준  
20195462     Star Wars: The Rise of Skywalker        J.J. 에이브럼스  
20196161                              TABALUGA      스벤 운터발트 주니어  
20196842  GIRLS und PANZER das FINALE : Part I         미즈시마 츠토무  
20191682                    Montmartre de Papa              민병우  
20190740                                                    정진호  
20190562                                                    강성옥  
20204089                     SIN TOMONOHAHA 01          카와사키 군지  
20191311                     The Child in Time          줄리언 파리노  
20193524                                                    원명준  
20194975                       Girls Encounter            에다 유카  
20204060               OKASARETEMOWASURENAI-01          하라다 칸토나  
20204101                KANASIMIYOKOTYO

In [200]:
# 참고 ) 이미 set_index 한 이후에 , 다시 하면 에러가 발생한다.
movieIDDF = movieIDDF.sort_values(by ="openDt")
movieIDDF = movieIDDF.set_index("movieCd")

In [201]:
# 원하는 순서대로 컬럼 변경
movieIDDF = movieIDDF[["openDt","year","month","day","movieNm","movieNmEn","directorpeopleNm"]]
movieIDDF

openDt  year month day               movieNm  \
movieCd                                                    
20192370  20200101  2020    01  01                  디어스킨   
20124722  20200101  2020    01  01             피아니스트의 전설   
20191035  20200102  2020    01  02                  무한정사   
20190770  20200102  2020    01  02              어린 이모 3    
20193870  20200106  2020    01  06     데릴사위 : 젊은 장모를 탐하다   
20193691  20200107  2020    01  07               스와핑 동창회   
20199581  20200108  2020    01  08                닥터 두리틀   
20203922  20200108  2020    01  08             아내의유혹-무삭제   
20196842  20200108  2020    01  08       걸즈 앤 판처 최종장 제1화   
20195462  20200108  2020    01  08    스타워즈: 라이즈 오브 스카이워커   
20196161  20200108  2020    01  08            타발루가와 얼음공주   
20190740  20200109  2020    01  09               어린 처형 3   
20204101  20200109  2020    01  09            꼬치집:과부 여주인   
20204060  20200109  2020    01  09       나쁜 섹스:겁탈 당한 아내3   
20197972  20200109  2020    01  09                  리틀 큐   
20193524  20200109  2020    01  09                수상한동거    
20190851  20200109  2020    01  09                   썩시드   
20204090  20200109  2020    01  09            애인:일본 유부녀들   
20190562  20200109  2020    01  09     울지마 톤즈 2 : 슈크란 바바   
20191311  20200109  2020    01  09              차일드 인 타임   
20204089  20200109  2020    01  09       친구엄마들:세 친구의 스와핑   
20194975  20200109  2020    01  09              소녀가 소녀에게   
20191682  20200109  2020    01  09               몽마르트 파파   
20193686  20200109  2020    01  09      잠 못 이루는 섹스2 무삭제판   
20192507  20200110  2020    01  10             도도녀 길들이기    
20197751  20200110  2020    01  10       무림방주: 절대고수의 탄생    
20193393  20200110  2020    01  10               어린 관리사    
20193184  20200112  2020    01  12               일 트로바토레   
20196670  20200115  2020    01  15           나쁜 녀석들: 포에버   
20183002  20200115  2020    01  15                 해치지않아   
20196674  20200116  2020    01  16                     갱   
20198676  20200116  2020    01  16           타오르는 여인의 초상   
20193478  20200116  2020    01  16                브라 이야기   
20180939  20200122  2020    01  22               남산의 부장들   
20192101  20200122  2020    01  22                   히트맨   
20192604  20200122  2020    01  22  오즈의 마법사: 요술구두와 말하는 책   
20188421  20200122  2020    01  22        미스터 주: 사라진 VIP   
20190009  20200130  2020    01  30                 카잔자키스   
20193321  20200212  2020    02  12                정직한 후보   
20192240  20200212  2020    02  12                작은 아씨들   

                                     movieNmEn directorpeopleNm  
movieCd                                                          
20192370                              Deerskin          Unknown  
20124722                    The Legend Of 1900        쥬세페 토르나토레  
20191035                                                    최재후  
20190770                                                Unknown  
20193870                                                    최민현  
20193691                                                    김석만  
20199581                              Dolittle           스티븐 개건  
20203922                                                    천성준  
20196842  GIRLS und PANZER das FINALE : Part I         미즈시마 츠토무  
20195462     Star Wars: The Rise of Skywalker        J.J. 에이브럼스  
20196161                              TABALUGA      스벤 운터발트 주니어  
20190740                                                    정진호  
20204101                KANASIMIYOKOTYOUNOONNA          카와사키 군지  
20204060               OKASARETEMOWASURENAI-01          하라다 칸토나  
20197972                              Little Q              나영창  
20193524                                                    원명준  
20190851                              SUCKSEED         차야놉 분프라콥  
20204090                       KYAKUTONERUTUMA          카와사키 군지  
20190562                                                    강성옥  
20191311                     The Child in Time          줄리언 파리노  
20204089                     SIN TOMONO

In [ ]:
# 엑셀 저장
# movieIDDF.to_excel("qqqq.xls")

상세정보 추가하기
- 영화 상세정보

In [130]:
# 02) JOSN Format : 2016 Open & 20item/perPage
movieCdInfoURL = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=675f83ad573ce1afad60b604dd62e6b4&movieCd=20124079"
movieCdInfoPage = urllib.request.urlopen(movieCdInfoURL)


movieCdInfoData = json.loads(movieCdInfoPage.read().decode('utf8'),encoding='utf-8')
# utf-8, utf8 둘다 가능
movieCdInfoData

{'movieInfoResult': {'movieInfo': {'movieCd': '20124079',
   'movieNm': '광해, 왕이 된 남자',
   'movieNmEn': 'Masquerade',
   'movieNmOg': '',
   'showTm': '131',
   'prdtYear': '2012',
   'openDt': '20120913',
   'prdtStatNm': '개봉',
   'typeNm': '장편',
   'nations': [{'nationNm': '한국'}],
   'genres': [{'genreNm': '사극'}, {'genreNm': '드라마'}],
   'directors': [{'peopleNm': '추창민', 'peopleNmEn': 'CHOO Chang-min'}],
   'actors': [{'peopleNm': '이병헌',
     'peopleNmEn': 'LEE Byung-hun',
     'cast': '광해/하선',
     'castEn': ''},
    {'peopleNm': '류승룡',
     'peopleNmEn': 'RYU Seung-ryong',
     'cast': '허균',
     'castEn': ''},
    {'peopleNm': '한효주',
     'peopleNmEn': 'HAN Hyo-joo',
     'cast': '중전',
     'castEn': ''},
    {'peopleNm': '장광',
     'peopleNmEn': 'JANG Kwang',
     'cast': '조내관',
     'castEn': ''},
    {'peopleNm': '김인권',
     'peopleNmEn': 'KIM In-kwon',
     'cast': '도부장',
     'castEn': ''},
    {'peopleNm': '심은경',
     'peopleNmEn': 'SHIM Eun-kyoung',
     'cast': '사월이',
     '

In [132]:
len(movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"])

33

In [157]:
movieCdInfoData["movieInfoResult"]["movieInfo"]["typeNm"]

'장편'

In [147]:
movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"][0]

{'peopleNm': '이병헌',
 'peopleNmEn': 'LEE Byung-hun',
 'cast': '광해/하선',
 'castEn': ''}

In [149]:
movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"][0]["peopleNm"]

'이병헌'

In [144]:
movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"][0]["cast"]

'광해/하선'

In [202]:
movieIDDF.head()

openDt  year month day            movieNm           movieNmEn  \
movieCd                                                                     
20192370  20200101  2020    01  01               디어스킨            Deerskin   
20124722  20200101  2020    01  01          피아니스트의 전설  The Legend Of 1900   
20191035  20200102  2020    01  02               무한정사                       
20190770  20200102  2020    01  02           어린 이모 3                        
20193870  20200106  2020    01  06  데릴사위 : 젊은 장모를 탐하다                       

         directorpeopleNm  
movieCd                    
20192370          Unknown  
20124722        쥬세페 토르나토레  
20191035              최재후  
20190770          Unknown  
20193870              최민현

In [203]:
movieIDDF["type"] = ""
movieIDDF["ActorNum"] = ""
movieIDDF["cast"] = ""
movieIDDF["cast_peopleNm"] = ""
movieIDDF.head()

openDt  year month day            movieNm           movieNmEn  \
movieCd                                                                     
20192370  20200101  2020    01  01               디어스킨            Deerskin   
20124722  20200101  2020    01  01          피아니스트의 전설  The Legend Of 1900   
20191035  20200102  2020    01  02               무한정사                       
20190770  20200102  2020    01  02           어린 이모 3                        
20193870  20200106  2020    01  06  데릴사위 : 젊은 장모를 탐하다                       

         directorpeopleNm type ActorNum cast cast_peopleNm  
movieCd                                                     
20192370          Unknown                                   
20124722        쥬세페 토르나토레                                   
20191035              최재후                                   
20190770          Unknown                                   
20193870              최민현

In [212]:
idx_type = movieIDDF.columns.get_loc("type")
idx_actorNum = movieIDDF.columns.get_loc("ActorNum")
idx_cast = movieIDDF.columns.get_loc("cast")
idx_actor = movieIDDF.columns.get_loc("cast_peopleNm")

In [222]:
for i in range(0, len(movieIDDF)):
    movieCd = movieIDDF.index[i]
    movieCdInfoURL = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=675f83ad573ce1afad60b604dd62e6b4&movieCd=" + movieCd 
    # print(movieCdInfoURL)
    movieCdInfoPage = urllib.request.urlopen(movieCdInfoURL)
    movieCdInfoData = json.loads(movieCdInfoPage.read().decode('utf8'),encoding='utf-8')
    
    # 장르 정보만 추가...
    if movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"] != []:
        movieIDDF.iat[i,idx_type ] = movieCdInfoData["movieInfoResult"]["movieInfo"]["typeNm"]
        movieIDDF.iat[i,idx_actorNum ] = len(movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"])
        movieIDDF.iat[i,idx_cast ] = movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"][0]["cast"]
        movieIDDF.iat[i,idx_actor ] = movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"][0]["peopleNm"]
    else :
        movieIDDF.iat[i,idx_type ] = movieCdInfoData["movieInfoResult"]["movieInfo"]["typeNm"]
        movieIDDF.iat[i,idx_actorNum ] = len(movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"])
        movieIDDF.iat[i,idx_cast ] = ""
        movieIDDF.iat[i,idx_actor ] = ""

In [223]:
movieIDDF.head(3)

openDt  year month day    movieNm           movieNmEn  \
movieCd                                                             
20192370  20200101  2020    01  01       디어스킨            Deerskin   
20124722  20200101  2020    01  01  피아니스트의 전설  The Legend Of 1900   
20191035  20200102  2020    01  02       무한정사                       

         directorpeopleNm type ActorNum                            cast  \
movieCd                                                                   
20192370          Unknown   장편        2                                   
20124722        쥬세페 토르나토레   장편        3  대니 부드만 T.D. 레몬 나인틴 헌드러드 1900 역   
20191035              최재후   장편        0                                   

         cast_peopleNm  
movieCd                 
20192370        장 뒤자르댕  
20124722          팀 로스  
20191035

In [194]:
movie_type = []
movie_actorNum = []
movie_cast = []
movie_actor = []

for i in range(0,len(movieLen)):
    movieCd = movieIDDF.index[i]
    
    movieCdInfoURL = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=675f83ad573ce1afad60b604dd62e6b4&movieCd=" + movieCd 
    movieCdInfoPage = urllib.request.urlopen(movieCdInfoURL)

    movieCdInfoData = json.loads(movieCdInfoPage.read().decode('utf8'),encoding='utf-8')

    movieCdInfoData
    
    if movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"] != []:
        movie_type.append(movieCdInfoData["movieInfoResult"]["movieInfo"]["typeNm"])
        movie_actorNum.append(len(movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"]))
        movie_cast.append(movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"][0]["cast"])
        movie_actor.append(movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"][0]["peopleNm"])
    else :
        movie_type.append(movieCdInfoData["movieInfoResult"]["movieInfo"]["typeNm"])
        movie_actorNum.append(len(movieCdInfoData["movieInfoResult"]["movieInfo"]["actors"]))
        movie_cast.append("")
        movie_actor.append("")


In [195]:
movieIDDF["type"] = movie_type
movieIDDF["ActorNum"] = movie_actorNum
movieIDDF["cast"] = movie_cast
movieIDDF["cast_peopleNm"] = movie_actor

movieIDDF

openDt  year month day               movieNm  \
movieCd                                                    
20192370  20200101  2020    01  01                  디어스킨   
20124722  20200101  2020    01  01             피아니스트의 전설   
20191035  20200102  2020    01  02                  무한정사   
20190770  20200102  2020    01  02              어린 이모 3    
20192392  20200106  2020    01  06             허락해버린 간호사   
20193870  20200106  2020    01  06     데릴사위 : 젊은 장모를 탐하다   
20193691  20200107  2020    01  07               스와핑 동창회   
20196842  20200108  2020    01  08       걸즈 앤 판처 최종장 제1화   
20196161  20200108  2020    01  08            타발루가와 얼음공주   
20203922  20200108  2020    01  08             아내의유혹-무삭제   
20199581  20200108  2020    01  08                닥터 두리틀   
20195462  20200108  2020    01  08    스타워즈: 라이즈 오브 스카이워커   
20204101  20200109  2020    01  09            꼬치집:과부 여주인   
20193686  20200109  2020    01  09      잠 못 이루는 섹스2 무삭제판   
20197972  20200109  2020    01  09                  리틀 큐   
20190851  20200109  2020    01  09                   썩시드   
20204090  20200109  2020    01  09            애인:일본 유부녀들   
20194975  20200109  2020    01  09              소녀가 소녀에게   
20204060  20200109  2020    01  09       나쁜 섹스:겁탈 당한 아내3   
20191311  20200109  2020    01  09              차일드 인 타임   
20204089  20200109  2020    01  09       친구엄마들:세 친구의 스와핑   
20190562  20200109  2020    01  09     울지마 톤즈 2 : 슈크란 바바   
20190740  20200109  2020    01  09               어린 처형 3   
20191682  20200109  2020    01  09               몽마르트 파파   
20193524  20200109  2020    01  09                수상한동거    
20197751  20200110  2020    01  10       무림방주: 절대고수의 탄생    
20193393  20200110  2020    01  10               어린 관리사    
20192507  20200110  2020    01  10             도도녀 길들이기    
20193184  20200112  2020    01  12               일 트로바토레   
20183002  20200115  2020    01  15                 해치지않아   
20196670  20200115  2020    01  15           나쁜 녀석들: 포에버   
20198676  20200116  2020    01  16           타오르는 여인의 초상   
20196674  20200116  2020    01  16                     갱   
20193478  20200116  2020    01  16                브라 이야기   
20192604  20200122  2020    01  22  오즈의 마법사: 요술구두와 말하는 책   
20180939  20200122  2020    01  22               남산의 부장들   
20192101  20200122  2020    01  22                   히트맨   
20188421  20200122  2020    01  22        미스터 주: 사라진 VIP   
20192240  20200212  2020    02  12                작은 아씨들   
20193321  20200212  2020    02  12                정직한 후보   

                                     movieNmEn directorpeopleNm type  \
movieCd                                                                
20192370                              Deerskin          Unknown   장편   
20124722                    The Legend Of 1900        쥬세페 토르나토레   장편   
20191035                                                    최재후   장편   
20190770                                                Unknown   장편   
20192392                    Kotsujiko-de Nyuin          Unknown   장편   
20193870                                                    최민현   장편   
20193691                                                    김석만   장편   
20196842  GIRLS und PANZER das FINALE : Part I         미즈시마 츠토무   장편   
20196161                              TABALUGA      스벤 운터발트 주니어   장편   
20203922                                                    천성준   장편   
20199581                              Dolittle           스티븐 개건   장편   
20195462     Star Wars: The Rise of Skywalker        J.J. 에이브럼스   장편   
20204101                KANASIMIYOKOTYOUNOONNA          카와사키 군지   장편   
20193686                                                    이민환   장편   
20197972                              Little Q              나영창   장편   
20190851                              SUCKSEED         차야놉 분프라콥   장편   
20204090                       KYAKUTONERUTUMA          카와사키 군지   장편   
20194975                       Girls Encounter            에다 유카   장편   
20204060               OKASARETEMOWASURENAI-01     

XML

python 3 : urllib

In [2]:
#### html / xml ####
# 01) packages
import urllib.request
from bs4 import BeautifulSoup
import pandas as pd

주의 ) 앞의 JSON 과 URL은 동일, 타입만 다르다.

In [3]:
# 02) use url
sampleURL = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieList.xml?key=675f83ad573ce1afad60b604dd62e6b4&openStartDt=2020&itemPerPage=100"

res = urllib.request.urlopen(sampleURL)
soup = BeautifulSoup(res, "html.parser")
print(res)
print(soup)

<?xml version="1.0" encoding="utf-8" standalone="yes"?><movielistresult><totcnt>88</totcnt><movielist><movie><moviecd>20192987</moviecd><movienm>스파이즈 </movienm><movienmen>Spycies</movienmen><prdtyear>2019</prdtyear><opendt>20200115</opendt><typenm>장편</typenm><prdtstatnm>개봉</prdtstatnm><nationalt>프랑스</nationalt><genrealt>애니메이션</genrealt><repnationnm>프랑스</repnationnm><repgenrenm>애니메이션</repgenrenm><directors><director><peoplenm>기욤 이베르넬</peoplenm></director></directors><companys></companys></movie><movie><moviecd>20192988</moviecd><movienm>슈퍼 베어 </movienm><movienmen>Super Bear</movienmen><prdtyear>2019</prdtyear><opendt>20200115</opendt><typenm>장편</typenm><prdtstatnm>개봉</prdtstatnm><nationalt>미국</nationalt><genrealt>액션,어드벤처,애니메이션</genrealt><repnationnm>미국</repnationnm><repgenrenm>액션</repgenrenm><directors></directors><companys></companys></movie><movie><moviecd>20188421</moviecd><movienm>미스터 주: 사라진 VIP</movienm><movienmen>MR. ZOO: THE MISSING VIP</movienmen><prdtyear>2018</prdtyear><opendt

In [4]:
# OS나 다른 환경에 의해서 웹브라우저로 보는 것과 다를 수 있으니 유의
print(soup.prettify())

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<movielistresult>
 <totcnt>
  88
 </totcnt>
 <movielist>
  <movie>
   <moviecd>
    20192987
   </moviecd>
   <movienm>
    스파이즈
   </movienm>
   <movienmen>
    Spycies
   </movienmen>
   <prdtyear>
    2019
   </prdtyear>
   <opendt>
    20200115
   </opendt>
   <typenm>
    장편
   </typenm>
   <prdtstatnm>
    개봉
   </prdtstatnm>
   <nationalt>
    프랑스
   </nationalt>
   <genrealt>
    애니메이션
   </genrealt>
   <repnationnm>
    프랑스
   </repnationnm>
   <repgenrenm>
    애니메이션
   </repgenrenm>
   <directors>
    <director>
     <peoplenm>
      기욤 이베르넬
     </peoplenm>
    </director>
   </directors>
   <companys>
   </companys>
  </movie>
  <movie>
   <moviecd>
    20192988
   </moviecd>
   <movienm>
    슈퍼 베어
   </movienm>
   <movienmen>
    Super Bear
   </movienmen>
   <prdtyear>
    2019
   </prdtyear>
   <opendt>
    20200115
   </opendt>
   <typenm>
    장편
   </typenm>
   <prdtstatnm>
    개봉
   </prdtstatnm>
   <nationalt>
 

In [5]:
soup.find_all("moviecd")[0]

<moviecd>20192987</moviecd>

In [6]:
soup.find_all("moviecd")[0].text

'20192987'

In [7]:
soup.find_all("moviecd")[0].get_text

<bound method Tag.get_text of <moviecd>20192987</moviecd>>

In [10]:
idx_moviecd = movieIDDF_temp.columns.get_loc("movieCd")
idx_movienm = movieIDDF_temp.columns.get_loc("movieNm")
idx_movienmen = movieIDDF_temp.columns.get_loc("movieNmEn")
idx_opendt = movieIDDF_temp.columns.get_loc("openDt")
idx_director = movieIDDF_temp.columns.get_loc("directorpeopleNm")

In [11]:
movieIDDF = pd.DataFrame()
movieIDDF_temp = pd.DataFrame()
movieIDDF_temp = movieIDDF_temp.append({"movieCd":"", "movieNm":"", "movieNmEn":"", "openDt":"", "directorpeopleNm":""}, ignore_index=True)
moviexml = int(soup.find("totcnt").text)

for i in range(0,moviexml):
    movieIDDF_temp.iat[0,idx_moviecd] = soup.find_all("moviecd")[i].text
    movieIDDF_temp.iat[0,idx_movienm] = soup.find_all("movienm")[i].text
    movieIDDF_temp.iat[0,idx_movienmen] = soup.find_all("movienmen")[i].text
    movieIDDF_temp.iat[0,idx_opendt] = soup.find_all("opendt")[i].text
    movieIDDF_temp.iat[0,idx_director] = soup.find_all("directors")[i].text
    
    
    movieIDDF = movieIDDF.append(movieIDDF_temp, ignore_index = True)
    
    movieIDDF_temp = pd.DataFrame()
    movieIDDF_temp = movieIDDF_temp.append({"movieCd":"", "movieNm":"", "movieNmEn":"", "openDt":"", "directorpeopleNm":""}, ignore_index=True)
    
movieIDDF

    

directorpeopleNm   movieCd               movieNm  \
0           기욤 이베르넬  20192987                 스파이즈    
1                    20192988                슈퍼 베어    
2               김태윤  20188421        미스터 주: 사라진 VIP   
3        닉 브루노트로이 콴  20192300             스파이 지니어스    
4                    20204340  시원찮은 그녀를 위한 육성방법 피날레   
..              ...       ...                   ...   
83                   20192387         꽉찬 느낌이 좋은 새엄마   
84                   20192335          꽃미모 며느리에게 갑질   
85              신해강  20186647             청춘빌라 살인사건   
86          브라이언 커크  20191408       21 브릿지: 테러 셧다운    
87    로레타 달포죠미셸 볼론테  20190809   마리오 보타 : 영혼을 위한 건축    

                                            movieNmEn    openDt  
0                                             Spycies  20200115  
1                                          Super Bear  20200115  
2                            MR. ZOO: THE MISSING VIP  20200122  
3                                   Spies in Disguise  20200122  
4                           Saekano the Movie: Finale  20200227  
..                                                ...       ...  
83  Secret relationship with mother-in-law. Invite...  20200103  
84                                    Yome Ryakudatsu  20200103  
85                                  Dogs in the House  20200102  
86                                         21 Bridges  20200101  
87                     Mario Bootta, The Space Beyond  20200123  

[88 rows x 5 columns]

In [12]:
movieIDDF["year"] = movieIDDF["openDt"].apply(lambda x : x[:4])
movieIDDF["month"] = movieIDDF["openDt"].apply(lambda x : x[4:6])
movieIDDF["day"] = movieIDDF["openDt"].apply(lambda x : x[6:])

In [13]:
movieIDDF

directorpeopleNm   movieCd               movieNm  \
0           기욤 이베르넬  20192987                 스파이즈    
1                    20192988                슈퍼 베어    
2               김태윤  20188421        미스터 주: 사라진 VIP   
3        닉 브루노트로이 콴  20192300             스파이 지니어스    
4                    20204340  시원찮은 그녀를 위한 육성방법 피날레   
..              ...       ...                   ...   
83                   20192387         꽉찬 느낌이 좋은 새엄마   
84                   20192335          꽃미모 며느리에게 갑질   
85              신해강  20186647             청춘빌라 살인사건   
86          브라이언 커크  20191408       21 브릿지: 테러 셧다운    
87    로레타 달포죠미셸 볼론테  20190809   마리오 보타 : 영혼을 위한 건축    

                                            movieNmEn    openDt  year month  \
0                                             Spycies  20200115  2020    01   
1                                          Super Bear  20200115  2020    01   
2                            MR. ZOO: THE MISSING VIP  20200122  2020    01   
3                                   Spies in Disguise  20200122  2020    01   
4                           Saekano the Movie: Finale  20200227  2020    02   
..                                                ...       ...   ...   ...   
83  Secret relationship with mother-in-law. Invite...  20200103  2020    01   
84                                    Yome Ryakudatsu  20200103  2020    01   
85                                  Dogs in the House  20200102  2020    01   
86                                         21 Bridges  20200101  2020    01   
87                     Mario Bootta, The Space Beyond  20200123  2020    01   

   day  
0   15  
1   15  
2   22  
3   22  
4   27  
..  ..  
83  03  
84  03  
85  02  
86  01  
87  23  

[88 rows x 8 columns]

In [14]:
movieIDDF = movieIDDF.sort_values(by ="openDt")
movieIDDF = movieIDDF.set_index("movieCd")

In [15]:
movieIDDF = movieIDDF[["openDt","year","month","day","movieNm","movieNmEn","directorpeopleNm"]]
movieIDDF

openDt  year month day               movieNm  \
movieCd                                                    
20191408  20200101  2020    01  01       21 브릿지: 테러 셧다운    
20192370  20200101  2020    01  01                  디어스킨   
20196412  20200101  2020    01  01                  파바로티   
20124722  20200101  2020    01  01             피아니스트의 전설   
20190770  20200102  2020    01  02              어린 이모 3    
...            ...   ...   ...  ..                   ...   
20190809  20200123  2020    01  23   마리오 보타 : 영혼을 위한 건축    
20190009  20200130  2020    01  30                 카잔자키스   
20192240  20200212  2020    02  12                작은 아씨들   
20193321  20200212  2020    02  12                정직한 후보   
20204340  20200227  2020    02  27  시원찮은 그녀를 위한 육성방법 피날레   

                               movieNmEn directorpeopleNm  
movieCd                                                    
20191408                      21 Bridges          브라이언 커크  
20192370                        Deerskin                   
20196412                       Pavarotti            론 하워드  
20124722              The Legend Of 1900        쥬세페 토르나토레  
20190770                                                   
...                                  ...              ...  
20190809  Mario Bootta, The Space Beyond    로레타 달포죠미셸 볼론테  
20190009                     Kazantzakis                   
20192240                    Little Women           그레타 거윅  
20193321                HONEST CANDIDATE              장유정  
20204340       Saekano the Movie: Finale                   

[88 rows x 7 columns]

In [16]:
movieIDDF["type"] = ""
movieIDDF["ActorNum"] = ""
movieIDDF["cast"] = ""
movieIDDF["cast_peopleNm"] = ""
movieIDDF.head()

openDt  year month day          movieNm           movieNmEn  \
movieCd                                                                   
20191408  20200101  2020    01  01  21 브릿지: 테러 셧다운           21 Bridges   
20192370  20200101  2020    01  01             디어스킨            Deerskin   
20196412  20200101  2020    01  01             파바로티           Pavarotti   
20124722  20200101  2020    01  01        피아니스트의 전설  The Legend Of 1900   
20190770  20200102  2020    01  02         어린 이모 3                        

         directorpeopleNm type ActorNum cast cast_peopleNm  
movieCd                                                     
20191408          브라이언 커크                                   
20192370                                                    
20196412            론 하워드                                   
20124722        쥬세페 토르나토레                                   
20190770

In [17]:
idx_type = movieIDDF.columns.get_loc("type")
idx_actorNum = movieIDDF.columns.get_loc("ActorNum")
idx_cast = movieIDDF.columns.get_loc("cast")
idx_actor = movieIDDF.columns.get_loc("cast_peopleNm")

In [18]:
for i in range(0, len(movieIDDF)):
    movieCd = movieIDDF.index[i]
    infourl = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.xml?key=675f83ad573ce1afad60b604dd62e6b4&movieCd=" + movieCd 
    res_detail = urllib.request.urlopen(infourl)
    soup_detail = BeautifulSoup(res_detail, "html.parser")
    # 장르 정보만 추가...
    movieIDDF.iat[i,idx_type ] = soup_detail.find_all("typenm")[0].text
    movieIDDF.iat[i,idx_actorNum ] = len(soup_detail.find_all("actor"))
    
    if soup_detail.find_all("actor") != []:
        movieIDDF.iat[i,idx_cast ] = soup_detail.find_all("cast")[0].text
        movieIDDF.iat[i,idx_actor ] = soup_detail.find_all("actor",{"peoplenm":""})[0].find_all("peoplenm")[0].text
    else :
        movieIDDF.iat[i,idx_cast ] = ""
        movieIDDF.iat[i,idx_actor ] = ""

In [19]:
movieIDDF

openDt  year month day               movieNm  \
movieCd                                                    
20191408  20200101  2020    01  01       21 브릿지: 테러 셧다운    
20192370  20200101  2020    01  01                  디어스킨   
20196412  20200101  2020    01  01                  파바로티   
20124722  20200101  2020    01  01             피아니스트의 전설   
20190770  20200102  2020    01  02              어린 이모 3    
...            ...   ...   ...  ..                   ...   
20190809  20200123  2020    01  23   마리오 보타 : 영혼을 위한 건축    
20190009  20200130  2020    01  30                 카잔자키스   
20192240  20200212  2020    02  12                작은 아씨들   
20193321  20200212  2020    02  12                정직한 후보   
20204340  20200227  2020    02  27  시원찮은 그녀를 위한 육성방법 피날레   

                               movieNmEn directorpeopleNm type ActorNum  \
movieCd                                                                   
20191408                      21 Bridges          브라이언 커크   장편        4   
20192370                        Deerskin                    장편        2   
20196412                       Pavarotti            론 하워드   장편        1   
20124722              The Legend Of 1900        쥬세페 토르나토레   장편        3   
20190770                                                    장편        0   
...                                  ...              ...  ...      ...   
20190809  Mario Bootta, The Space Beyond    로레타 달포죠미셸 볼론테   장편        4   
20190009                     Kazantzakis                    장편        1   
20192240                    Little Women           그레타 거윅   장편        7   
20193321                HONEST CANDIDATE              장유정   장편       13   
20204340       Saekano the Movie: Finale                    장편        1   

                                    cast   cast_peopleNm  
movieCd                                                   
20191408                                         채드윅 보스만  
20192370                                          장 뒤자르댕  
20196412                                       루치아노 파바로티  
20124722  대니 부드만 T.D. 레몬 나인틴 헌드러드 1900 역            팀 로스  
20190770                                                  
...                                  ...             ...  
20190809                                          마리오 보타  
20190009                                  오디세즈 파파스필리오풀로스  
20192240                                          시얼샤 로넌  
20193321                                             라미란  
20204340                          아키 토모야       마츠오카 요시츠구  

[88 rows x 11 columns]

In [20]:
movieIDDF

openDt  year month day               movieNm  \
movieCd                                                    
20191408  20200101  2020    01  01       21 브릿지: 테러 셧다운    
20192370  20200101  2020    01  01                  디어스킨   
20196412  20200101  2020    01  01                  파바로티   
20124722  20200101  2020    01  01             피아니스트의 전설   
20190770  20200102  2020    01  02              어린 이모 3    
...            ...   ...   ...  ..                   ...   
20190809  20200123  2020    01  23   마리오 보타 : 영혼을 위한 건축    
20190009  20200130  2020    01  30                 카잔자키스   
20192240  20200212  2020    02  12                작은 아씨들   
20193321  20200212  2020    02  12                정직한 후보   
20204340  20200227  2020    02  27  시원찮은 그녀를 위한 육성방법 피날레   

                               movieNmEn directorpeopleNm type ActorNum  \
movieCd                                                                   
20191408                      21 Bridges          브라이언 커크   장편        4   
20192370                        Deerskin                    장편        2   
20196412                       Pavarotti            론 하워드   장편        1   
20124722              The Legend Of 1900        쥬세페 토르나토레   장편        3   
20190770                                                    장편        0   
...                                  ...              ...  ...      ...   
20190809  Mario Bootta, The Space Beyond    로레타 달포죠미셸 볼론테   장편        4   
20190009                     Kazantzakis                    장편        1   
20192240                    Little Women           그레타 거윅   장편        7   
20193321                HONEST CANDIDATE              장유정   장편       13   
20204340       Saekano the Movie: Finale                    장편        1   

                                    cast   cast_peopleNm  
movieCd                                                   
20191408                                         채드윅 보스만  
20192370                                          장 뒤자르댕  
20196412                                       루치아노 파바로티  
20124722  대니 부드만 T.D. 레몬 나인틴 헌드러드 1900 역            팀 로스  
20190770                                                  
...                                  ...             ...  
20190809                                          마리오 보타  
20190009                                  오디세즈 파파스필리오풀로스  
20192240                                          시얼샤 로넌  
20193321                                             라미란  
20204340                          아키 토모야       마츠오카 요시츠구  

[88 rows x 11 columns]

In [307]:
datailurl = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.xml?key=675f83ad573ce1afad60b604dd62e6b4&movieCd=20152782"

resTest = urllib.request.urlopen(datailurl)
soupTest = BeautifulSoup(resTest,"html.parser")
print(soupTest.prettify())

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<movieinforesult>
 <movieinfo>
  <moviecd>
   20152782
  </moviecd>
  <movienm>
   날, 보러와요
  </movienm>
  <movienmen>
   INSANE
  </movienmen>
  <movienmog>
  </movienmog>
  <showtm>
   90
  </showtm>
  <prdtyear>
   2015
  </prdtyear>
  <opendt>
   20160407
  </opendt>
  <prdtstatnm>
   개봉
  </prdtstatnm>
  <typenm>
   장편
  </typenm>
  <nations>
   <nation>
    <nationnm>
     한국
    </nationnm>
   </nation>
  </nations>
  <genres>
   <genre>
    <genrenm>
     미스터리
    </genrenm>
   </genre>
   <genre>
    <genrenm>
     스릴러
    </genrenm>
   </genre>
  </genres>
  <directors>
   <director>
    <peoplenm>
     이철하
    </peoplenm>
    <peoplenmen>
     LEE Cheol-ha
    </peoplenmen>
   </director>
  </directors>
  <actors>
   <actor>
    <peoplenm>
     강예원
    </peoplenm>
    <peoplenmen>
     KANG Ye-won
    </peoplenmen>
    <cast>
     강수아
    </cast>
    <casten>
     Su-a
    </casten>
   </actor>
   <actor>
    <peoplenm>


In [314]:
soupTest.find_all("director",{"peoplenm":""})[0].text

'이철하LEE Cheol-ha'