In [1]:
import numpy as np

In [2]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [4]:
arr = arr.reshape((4,8))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [5]:
print(arr)
print(arr.T)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
[[ 0  8 16 24]
 [ 1  9 17 25]
 [ 2 10 18 26]
 [ 3 11 19 27]
 [ 4 12 20 28]
 [ 5 13 21 29]
 [ 6 14 22 30]
 [ 7 15 23 31]]


In [6]:
import pandas as pd

In [10]:
stock_price_list = [10000,10350,10100,9600,10500,11350]
stock_price_Series = pd.Series([10000,10350,10100,9600,10500,11350])

stock_price_Series

0    10000
1    10350
2    10100
3     9600
4    10500
5    11350
dtype: int64

In [14]:
stock_price_list[1]
stock_price_list[1:3]

[10350, 10100]

In [15]:
stock_price_Series[1]
stock_price_Series[1:3]

1    10350
2    10100
dtype: int64

In [16]:
stock_price_Series_withIndex = pd.Series([10000,10350,10100,9600,10500,11350],
    index = ["2016-03-01","2016-03-02","2016-03-04","2016-03-05","2016-03-06","2016-03-07"])

In [17]:
stock_price_Series_withIndex

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
2016-03-06    10500
2016-03-07    11350
dtype: int64

In [19]:
stock_price_Series_withIndex["2016-03-04"]

10100

In [20]:
stock_price_Series_withIndex.index

Index(['2016-03-01', '2016-03-02', '2016-03-04', '2016-03-05', '2016-03-06',
       '2016-03-07'],
      dtype='object')

In [21]:
len(stock_price_Series_withIndex)

6

In [22]:
stock_price_Series_withIndex.values

array([10000, 10350, 10100,  9600, 10500, 11350], dtype=int64)

In [33]:
for i in range(0,len(stock_price_Series_withIndex)):
    print("Index : ",stock_price_Series_withIndex.index[i])
    print("values : ",stock_price_Series_withIndex.values[i])

Index :  2016-03-01
values :  10000
Index :  2016-03-02
values :  10350
Index :  2016-03-04
values :  10100
Index :  2016-03-05
values :  9600
Index :  2016-03-06
values :  10500
Index :  2016-03-07
values :  11350


In [29]:
for idx, value in enumerate(stock_price_Series_withIndex):
    print(idx)
    print(value)

0
10000
1
10350
2
10100
3
9600
4
10500
5
11350


In [32]:
for i in range(0,len(stock_price_Series_withIndex)):
    print(stock_price_Series_withIndex.index[i])
    print(stock_price_Series_withIndex.values[i])

2016-03-01
10000
2016-03-02
10350
2016-03-04
10100
2016-03-05
9600
2016-03-06
10500
2016-03-07
11350


In [34]:
for i in stock_price_Series_withIndex.index:
    print(i)
    print(stock_price_Series_withIndex[i])

2016-03-01
10000
2016-03-02
10350
2016-03-04
10100
2016-03-05
9600
2016-03-06
10500
2016-03-07
11350


In [35]:
stock_price_Series_withIndex[[0,3]]

2016-03-01    10000
2016-03-05     9600
dtype: int64

In [36]:
stock_price_Series_withIndex[["2016-03-02","2016-03-06"]]

2016-03-02    10350
2016-03-06    10500
dtype: int64

In [37]:
stock_price_list[0]

10000

In [38]:
stock_price_list[0:3]

[10000, 10350, 10100]

In [39]:
stock_price_list[[3,5]]

TypeError: list indices must be integers or slices, not list

In [40]:
search_index = [3,5]
[stock_price_list[i] for i in search_index]

[9600, 11350]

In [41]:
stock_price_Series_withIndex*2

2016-03-01    20000
2016-03-02    20700
2016-03-04    20200
2016-03-05    19200
2016-03-06    21000
2016-03-07    22700
dtype: int64

In [42]:
stock_price_Series_withIndex>10500

2016-03-01    False
2016-03-02    False
2016-03-04    False
2016-03-05    False
2016-03-06    False
2016-03-07     True
dtype: bool

In [43]:
stock_price_Series_withIndex[stock_price_Series_withIndex>10500]

2016-03-07    11350
dtype: int64

In [47]:
print(stock_price_Series_withIndex)
print("_____________________")
print("2016-03-05" in stock_price_Series_withIndex)

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
2016-03-06    10500
2016-03-07    11350
dtype: int64
_____________________
True


In [45]:
9600 in stock_price_Series_withIndex

False

In [46]:
"2016-03-5" in stock_price_Series_withIndex

False

In [52]:
sdata = {"APPLE":5000, "MS":2000, "AMAZON":4500}
obj3 = pd.Series(sdata)
print(obj3)

APPLE     5000
MS        2000
AMAZON    4500
dtype: int64


In [53]:
states = ["GOOGLE", "APPLE", "AMAZON"]
obj4 = pd.Series(sdata, states)
print(obj4)

GOOGLE       NaN
APPLE     5000.0
AMAZON    4500.0
dtype: float64


In [54]:
print(obj3 + obj4)
print(obj3 - obj4)

AMAZON     9000.0
APPLE     10000.0
GOOGLE        NaN
MS            NaN
dtype: float64
AMAZON    0.0
APPLE     0.0
GOOGLE    NaN
MS        NaN
dtype: float64


In [56]:
stock_price_Series_withIndex.iat[0]

10000

In [57]:
stock_price_Series_withIndex.at["2016-03-01"]

10000

In [65]:
print(stock_price_Series_withIndex.iloc[0:3])
print()
print(stock_price_Series_withIndex.iloc[[0,3]])

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
dtype: int64

2016-03-01    10000
2016-03-05     9600
dtype: int64


In [63]:
print(stock_price_Series_withIndex.loc["2016-03-01":"2016-03-05"])
print()
print(stock_price_Series_withIndex.loc[["2016-03-01","2016-03-05"]])

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
dtype: int64

2016-03-01    10000
2016-03-05     9600
dtype: int64


In [67]:
print(stock_price_Series_withIndex.count())
print(len(stock_price_Series_withIndex))

6
6


In [68]:
add_data = pd.Series([12100], index=["2016-03-08"])
print(stock_price_Series_withIndex.append(add_data))
print(stock_price_Series_withIndex)

2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
2016-03-06    10500
2016-03-07    11350
2016-03-08    12100
dtype: int64
2016-03-01    10000
2016-03-02    10350
2016-03-04    10100
2016-03-05     9600
2016-03-06    10500
2016-03-07    11350
dtype: int64


In [76]:
add_data = pd.Series([10000], index=["2016-03-05"])
print(stock_price_Series_withIndex.append(add_data, verify_integrity=True))  #verify_integrity=True -> 중복값이 있을 경우 넣을 수 없다
print(stock_price_Series_withIndex)

ValueError: Indexes have overlapping values: Index(['2016-03-05'], dtype='object')

In [101]:
d = [0,1,2,3,4]
df = pd.DataFrame(d)
print(df)
print()
ds = pd.Series(d)
print(ds)

   0
0  0
1  1
2  2
3  3
4  4

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [102]:
df.columns = ["column1"]
print(df)

   column1
0        0
1        1
2        2
3        3
4        4


In [103]:
df["newCol"] = d
print(df)
print()
df["newCol2"] = 5
print(df)

   column1  newCol
0        0       0
1        1       1
2        2       2
3        3       3
4        4       4

   column1  newCol  newCol2
0        0       0        5
1        1       1        5
2        2       2        5
3        3       3        5
4        4       4        5


In [104]:
df["newCol3"] = df.newCol2
print(df)

df["newCol3"] = df.newCol3 * 100
print(df)

   column1  newCol  newCol2  newCol3
0        0       0        5        5
1        1       1        5        5
2        2       2        5        5
3        3       3        5        5
4        4       4        5        5
   column1  newCol  newCol2  newCol3
0        0       0        5      500
1        1       1        5      500
2        2       2        5      500
3        3       3        5      500
4        4       4        5      500


In [105]:
print(df.iloc[1,2])

df.iloc[1,2] = 2000
print(df)

5
   column1  newCol  newCol2  newCol3
0        0       0        5      500
1        1       1     2000      500
2        2       2        5      500
3        3       3        5      500
4        4       4        5      500


In [106]:
print(df)

del df["column1"]
print(df)

   column1  newCol  newCol2  newCol3
0        0       0        5      500
1        1       1     2000      500
2        2       2        5      500
3        3       3        5      500
4        4       4        5      500
   newCol  newCol2  newCol3
0       0        5      500
1       1     2000      500
2       2        5      500
3       3        5      500
4       4        5      500


In [112]:
print(df.columns.values)
newColList = ['newCol2', 'newCol3']
df[newColList]

['newCol' 'newCol2' 'newCol3']


newCol2  newCol3
0        5      500
1     2000      500
2        5      500
3        5      500
4        5      500

In [111]:
stock_price_DF_withIndex = pd.DataFrame([10000,10350,10100,9600,10500,11350],
    index = ["2016-03-01","2016-03-02","2016-03-04","2016-03-05","2016-03-06","2016-03-07"])

stock_price_DF_withIndex

0
2016-03-01  10000
2016-03-02  10350
2016-03-04  10100
2016-03-05   9600
2016-03-06  10500
2016-03-07  11350

In [113]:
stock_price_DF_withIndex.rename(columns={"0":"시가"}, inplace = True)
stock_price_DF_withIndex

0
2016-03-01  10000
2016-03-02  10350
2016-03-04  10100
2016-03-05   9600
2016-03-06  10500
2016-03-07  11350

In [114]:
stock_price_DF_withIndex.rename(columns={0:"시가"}, inplace = True)
stock_price_DF_withIndex

시가
2016-03-01  10000
2016-03-02  10350
2016-03-04  10100
2016-03-05   9600
2016-03-06  10500
2016-03-07  11350

In [116]:
stock_price_DF_withIndex["종가"] = [11000, 12000, 10000, 13000, 12000, 11000]
stock_price_DF_withIndex["고가"] = [12000, 12500, 10800, 13000, 12900, 11700]
stock_price_DF_withIndex["저가"] = [10000, 10000, 9500, 11500, 11000, 9900]
stock_price_DF_withIndex

시가     종가     고가     저가
2016-03-01  10000  11000  12000  10000
2016-03-02  10350  12000  12500  10000
2016-03-04  10100  10000  10800   9500
2016-03-05   9600  13000  13000  11500
2016-03-06  10500  12000  12900  11000
2016-03-07  11350  11000  11700   9900

In [117]:
stock_price_DF_withIndex.iat[0] # 2차원 데이터이기 때문에 오류발생

TypeError: _get_value() missing 1 required positional argument: 'col'

In [118]:
stock_price_DF_withIndex.iat[0,3]

10000

In [120]:
stock_price_DF_withIndex.loc["2016-03-01",["시가","종가"]]

시가    10000
종가    11000
Name: 2016-03-01, dtype: int64

In [127]:
stock_price_DF_withIndex.loc["2016-03-01":"2016-03-04", ]

시가     종가     고가     저가
2016-03-01  10000  11000  12000  10000
2016-03-02  10350  12000  12500  10000
2016-03-04  10100  10000  10800   9500

In [129]:
stock_price_DF_withIndex.values

array([[10000, 11000, 12000, 10000],
       [10350, 12000, 12500, 10000],
       [10100, 10000, 10800,  9500],
       [ 9600, 13000, 13000, 11500],
       [10500, 12000, 12900, 11000],
       [11350, 11000, 11700,  9900]], dtype=int64)

In [130]:
stock_price_DF_withIndex.shape

(6, 4)

In [133]:
stock_price_DF_withIndex.shape[1]

4

In [134]:
stock_price_DF_withIndex.size

24

In [136]:
stock_price_DF_withIndex.ndim

2

In [137]:
obj = pd.Series([4.5,7.2,-5.3], index=["c","b","a"])
obj

c    4.5
b    7.2
a   -5.3
dtype: float64

In [138]:
obj2 = obj.reindex(["a","b","c","d","e"])
obj2

a   -5.3
b    7.2
c    4.5
d    NaN
e    NaN
dtype: float64

In [139]:
obj.reindex(["a","b"])

a   -5.3
b    7.2
dtype: float64

In [141]:
obj.reindex(["a","b","c","d","e"], fill_value=0)

a   -5.3
b    7.2
c    4.5
d    0.0
e    0.0
dtype: float64

In [143]:
# 보간법
obj = pd.Series([4.5,7.2,-5.3], index=["c","b","a"])
print(obj)
print("---------------")
print(obj.reindex(["a","d","e","c","b"]))
print("---------------")
print(obj.reindex(["a","d","e","c","b"]).interpolate())

c    4.5
b    7.2
a   -5.3
dtype: float64
---------------
a   -5.3
d    NaN
e    NaN
c    4.5
b    7.2
dtype: float64
---------------
a   -5.300000
d   -2.033333
e    1.233333
c    4.500000
b    7.200000
dtype: float64


In [149]:
df = pd.DataFrame([4.5,7.2,-5.3], index=["c","b","a"])
df = df.reindex(["a","d","e","c","b"])
print(df)
print("---------------")
df["interPo"] = df.iloc[:,0].interpolate()
print(df)

     0
a -5.3
d  NaN
e  NaN
c  4.5
b  7.2
---------------
     0   interPo
a -5.3 -5.300000
d  NaN -2.033333
e  NaN  1.233333
c  4.5  4.500000
b  7.2  7.200000
